# Generated by Django 3.2.12 on 2022-02-10 14:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coder", "0002_auto_20220209_2017"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="snippet",
            name="public_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
