# Generated by Django 3.2.12 on 2022-02-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0005_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='tags',
            field=models.ManyToManyField(blank=True, to='coder.Tag'),
        ),
    ]
