# Generated by Django 3.2.11 on 2022-01-25 16:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("shipper", "0001_initial"),
        ("shipper", "0002_auto_20211229_1205"),
        ("shipper", "0003_auto_20211230_0750"),
        ("shipper", "0004_portmanteau"),
        ("shipper", "0005_alter_ship_options"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name_1", models.CharField(max_length=100)),
                ("name_2", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Portmanteau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_parent", models.CharField(max_length=100)),
                ("first_index", models.SmallIntegerField()),
                ("first_flag_onwards", models.BooleanField()),
                ("second_parent", models.CharField(max_length=100)),
                ("second_index", models.SmallIntegerField()),
                ("second_flag_onwards", models.BooleanField()),
                ("is_inverted", models.BooleanField()),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portmanteaus",
                        to="shipper.ship",
                    ),
                ),
            ],
        ),
    ]
