# Generated by Django 3.2.10 on 2021-12-28 21:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name_a', models.CharField(max_length=100)),
                ('last_name_a', models.CharField(max_length=100)),
                ('first_name_b', models.CharField(max_length=100)),
                ('last_name_b', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
