# Generated by Django 3.2.10 on 2021-12-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='last_name_a',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='last_name_b',
        ),
    ]
