# Generated by Django 3.2.10 on 2021-12-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0002_auto_20211229_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ship',
            old_name='first_name_a',
            new_name='name_1',
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='first_name_b',
            new_name='name_2',
        ),
    ]
