# Generated by Django 3.2.11 on 2022-01-17 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0003_auto_20211230_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portmanteau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_parent', models.CharField(max_length=100)),
                ('first_index', models.SmallIntegerField()),
                ('first_flag_onwards', models.BooleanField()),
                ('second_parent', models.CharField(max_length=100)),
                ('second_index', models.SmallIntegerField()),
                ('second_flag_onwards', models.BooleanField()),
                ('is_inverted', models.BooleanField()),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portmanteaus', to='shipper.ship')),
            ],
        ),
    ]
