# Generated by Django 3.2.11 on 2022-01-17 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0004_portmanteau'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ship',
            options={'ordering': ['-created_at']},
        ),
    ]
