# Generated by Django 3.2.11 on 2022-01-25 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import project_manager.models


class Migration(migrations.Migration):

    replaces = [('project_manager', '0001_initial'), ('project_manager', '0002_auto_20210409_1409'), ('project_manager', '0003_auto_20210801_2248'), ('project_manager', '0004_alter_card_assigned_to'), ('project_manager', '0005_auto_20210803_1112'), ('project_manager', '0006_auto_20210803_1250'), ('project_manager', '0007_alter_timeentry_stopped_at'), ('project_manager', '0008_auto_20210803_1517'), ('project_manager', '0009_alter_timeentry_duration'), ('project_manager', '0010_auto_20210804_1639'), ('project_manager', '0011_bucket_auto_status'), ('project_manager', '0012_alter_bucket_auto_status'), ('project_manager', '0013_theme'), ('project_manager', '0014_auto_20210805_1744'), ('project_manager', '0015_alter_theme_name'), ('project_manager', '0016_auto_20210805_1802'), ('project_manager', '0017_card_color'), ('project_manager', '0018_bucket_color'), ('project_manager', '0019_auto_20210806_1119'), ('project_manager', '0020_auto_20210806_1125'), ('project_manager', '0021_alter_project_deadline'), ('project_manager', '0022_auto_20210806_1141'), ('project_manager', '0023_icon_notification'), ('project_manager', '0024_auto_20210806_1629'), ('project_manager', '0025_auto_20210806_1629'), ('project_manager', '0026_invite'), ('project_manager', '0027_alter_invite_email'), ('project_manager', '0028_alter_card_files'), ('project_manager', '0029_alter_invite_project'), ('project_manager', '0030_alter_timeentry_started_at'), ('project_manager', '0031_auto_20210814_1950'), ('project_manager', '0032_board_bucket_width'), ('project_manager', '0033_board_dark'), ('project_manager', '0034_auto_20210816_1446'), ('project_manager', '0035_auto_20210816_2053'), ('project_manager', '0036_alter_item_options'), ('project_manager', '0037_auto_20210818_1202'), ('project_manager', '0038_alter_tag_icon'), ('project_manager', '0039_tag_board'), ('project_manager', '0040_alter_card_tag'), ('project_manager', '0041_alter_card_tag'), ('project_manager', '0042_alter_card_tag'), ('project_manager', '0043_tag_unique_tag'), ('project_manager', '0044_tag_color'), ('project_manager', '0045_comment'), ('project_manager', '0046_auto_20210820_1631'), ('project_manager', '0047_alter_comment_options'), ('project_manager', '0048_alter_comment_options'), ('project_manager', '0049_alter_timeentry_started_at'), ('project_manager', '0050_card_due_date'), ('project_manager', '0051_bucket_updated_at'), ('project_manager', '0052_board_updated_at'), ('project_manager', '0053_board_background_image'), ('project_manager', '0054_auto_20210909_1619'), ('project_manager', '0055_alter_cardfile_card'), ('project_manager', '0056_alter_cardfile_file'), ('project_manager', '0057_auto_20211012_0011'), ('project_manager', '0058_board_time_entries_feature'), ('project_manager', '0059_delete_notification'), ('project_manager', '0060_invite_unique_email_by_project'), ('project_manager', '0061_remove_invite_unique_email_by_project'), ('project_manager', '0062_alter_card_description')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_boards', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.project')),
                ('compact', models.BooleanField(default=False)),
                ('fullscreen', models.BooleanField(default=False)),
                ('bucket_width', models.IntegerField(default=300)),
                ('dark', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'ordering': ['project', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('active', models.BooleanField(default=True)),
                ('primary', models.CharField(default=1, max_length=7, verbose_name='primary')),
                ('dark', models.CharField(default=1, max_length=7, verbose_name='dark')),
                ('light', models.CharField(default=1, max_length=7, verbose_name='light')),
            ],
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.board')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('auto_status', models.CharField(choices=[('N', 'No automatic status'), ('NS', 'Not started'), ('IP', 'In progress'), ('C', 'Completed')], default='N', max_length=2, verbose_name='status')),
                ('color', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_manager.theme')),
            ],
            options={
                'abstract': False,
                'ordering': ['board__project', 'board', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'icon',
                'verbose_name_plural': 'icons',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('read_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('action', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('active', models.BooleanField(default=True)),
                ('icon', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_manager.icon')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_manager_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to=project_manager.models.Card._card_directory_path)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_cards', to=settings.AUTH_USER_MODEL)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.bucket')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_cards', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='started_cards', to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('NS', 'Not started'), ('IP', 'In progress'), ('C', 'Completed')], default='NS', max_length=2, verbose_name='status')),
                ('color', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_manager.theme')),
            ],
            options={
                'abstract': False,
                'ordering': ['bucket__board__project', 'bucket__board', 'bucket', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_project_invites', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_invites', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_manager.project')),
            ],
            options={
                'verbose_name': 'invite',
                'verbose_name_plural': 'invites',
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.card')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('duration', models.DurationField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'time entry',
                'verbose_name_plural': 'time entries',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('checked_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.card')),
                ('checked_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_items', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('icon', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_manager.icon')),
                ('board', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_manager.board')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='card',
            name='tag',
            field=models.ManyToManyField(blank=True, default=None, to='project_manager.Tag'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('board', 'name'), name='unique_tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_manager.theme'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.card')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='card',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bucket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='board',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='board',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=project_manager.models.Board._background_image_path),
        ),
        migrations.RemoveField(
            model_name='card',
            name='files',
        ),
        migrations.CreateModel(
            name='CardFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=0, max_length=1000, upload_to=project_manager.models.CardFile._card_directory_path)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project_manager.card')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='assignees_feature',
            field=models.BooleanField(default=True, help_text='Enables assignees on cards'),
        ),
        migrations.AddField(
            model_name='board',
            name='checklist_feature',
            field=models.BooleanField(default=True, help_text='Enables checklist on cards'),
        ),
        migrations.AddField(
            model_name='board',
            name='color_feature',
            field=models.BooleanField(default=True, help_text='Enables color on cards'),
        ),
        migrations.AddField(
            model_name='board',
            name='comments_feature',
            field=models.BooleanField(default=True, help_text='Enables users to comment on cards'),
        ),
        migrations.AddField(
            model_name='board',
            name='due_date_feature',
            field=models.BooleanField(default=True, help_text='Enables cards to have due dates'),
        ),
        migrations.AddField(
            model_name='board',
            name='files_feature',
            field=models.BooleanField(default=True, help_text='Enables file attachments on cards'),
        ),
        migrations.AddField(
            model_name='board',
            name='status_feature',
            field=models.BooleanField(default=True, help_text='Enables status on cards'),
        ),
        migrations.AddField(
            model_name='board',
            name='tags_feature',
            field=models.BooleanField(default=True, help_text='Enables taga on cards'),
        ),
        migrations.AddField(
            model_name='board',
            name='time_entries_feature',
            field=models.BooleanField(default=True, help_text='Enables users to track time spent on cards'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddConstraint(
            model_name='invite',
            constraint=models.UniqueConstraint(fields=('email', 'project'), name='unique_email_by_project'),
        ),
        migrations.RemoveConstraint(
            model_name='invite',
            name='unique_email_by_project',
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
