# Generated by Django 4.2.5 on 2023-09-20 19:22

import django.db.models.deletion
import django.utils.timezone
import project_manager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=project_manager.models.Board._background_image_path,
                    ),
                ),
                (
                    "tags_feature",
                    models.BooleanField(
                        default=True, help_text="Enables tags on cards"
                    ),
                ),
                (
                    "color_feature",
                    models.BooleanField(
                        default=True, help_text="Enables color on cards"
                    ),
                ),
                (
                    "due_date_feature",
                    models.BooleanField(
                        default=True,
                        help_text="Enables cards to have due dates",
                    ),
                ),
                (
                    "status_feature",
                    models.BooleanField(
                        default=True, help_text="Enables status on cards"
                    ),
                ),
                (
                    "assignees_feature",
                    models.BooleanField(
                        default=True, help_text="Enables assignees on cards"
                    ),
                ),
                (
                    "checklist_feature",
                    models.BooleanField(
                        default=True, help_text="Enables checklist on cards"
                    ),
                ),
                (
                    "files_feature",
                    models.BooleanField(
                        default=True,
                        help_text="Enables file attachments on cards",
                    ),
                ),
                (
                    "comments_feature",
                    models.BooleanField(
                        default=True,
                        help_text="Enables users to comment on cards",
                    ),
                ),
                (
                    "time_entries_feature",
                    models.BooleanField(
                        default=True,
                        help_text="Enables users to track time spent on cards",
                    ),
                ),
                (
                    "assigned_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_boards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["project", "order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Bucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                ("order", models.IntegerField()),
                (
                    "description",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "auto_status",
                    models.CharField(
                        choices=[
                            ("N", "No automatic status"),
                            ("NS", "Not started"),
                            ("IP", "In progress"),
                            ("C", "Completed"),
                        ],
                        default="N",
                        max_length=2,
                        verbose_name="status",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_manager.board",
                    ),
                ),
            ],
            options={
                "ordering": ["board__project", "board", "order"],
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                ("order", models.IntegerField()),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NS", "Not started"),
                            ("IP", "In progress"),
                            ("C", "Completed"),
                        ],
                        default="NS",
                        max_length=2,
                        verbose_name="status",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bucket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_manager.bucket",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "bucket__board__project",
                    "bucket__board",
                    "bucket",
                    "order",
                ],
            },
        ),
        migrations.CreateModel(
            name="Icon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("markup", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "icon",
                "verbose_name_plural": "icons",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("order", models.IntegerField(default=1)),
                (
                    "assigned_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "primary",
                    models.CharField(max_length=7, verbose_name="primary"),
                ),
                ("dark", models.CharField(max_length=7, verbose_name="dark")),
                ("light", models.CharField(max_length=7, verbose_name="light")),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "started_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration",
                    models.DurationField(blank=True, editable=False, null=True),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_manager.card",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "time entry",
                "verbose_name_plural": "time entries",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_manager.board",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_manager.theme",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_manager.icon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spaces",
                        to="project_manager.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                ("order", models.IntegerField()),
                (
                    "checked_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_manager.card",
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=1000, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_project_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_project_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_manager.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "invite",
                "verbose_name_plural": "invites",
            },
        ),
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("compact", models.BooleanField(default=False)),
                ("dark", models.BooleanField(default=False)),
                ("bucket_width", models.IntegerField(default=300)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_manager_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "configuration",
                "verbose_name_plural": "configurations",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_manager.card",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CardFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=1000,
                        upload_to=project_manager.models.CardFile._card_directory_path,
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="project_manager.card",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="card",
            name="color",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project_manager.theme",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completed_cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="started_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="started_cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="tag",
            field=models.ManyToManyField(
                blank=True, default=None, to="project_manager.tag"
            ),
        ),
        migrations.AddField(
            model_name="bucket",
            name="color",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project_manager.theme",
            ),
        ),
        migrations.AddField(
            model_name="bucket",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="project_manager.project",
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="space",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_manager.space",
            ),
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create_card", "%(user)s created card"),
                            (
                                "update_name",
                                "%(user)s updated card name from %(old)s to %(new)s",
                            ),
                            (
                                "update_description",
                                "%(user)s updated card description",
                            ),
                            (
                                "update_due_date",
                                "%(user)s updated card due date from %(old)s to %(new)s",
                            ),
                            (
                                "update_status",
                                "%(user)s updated card status from %(old)s to %(new)s",
                            ),
                            (
                                "update_color",
                                "%(user)s updated card color from %(old)s to %(new)s",
                            ),
                            ("add_tags", "%(user)s added tag %(tag)s"),
                            ("remove_tags", "%(user)s removed tag %(tag)s"),
                            (
                                "add_assigned_user",
                                "%(user)s assigned %(assignee)s to card",
                            ),
                            (
                                "remove_assigned_user",
                                "%(user)s removed %(assignee)s from card's assigned users",
                            ),
                            (
                                "add_checklist_item",
                                "%(user)s added checklist item %(item)s",
                            ),
                            (
                                "update_checklist_item",
                                "%(user)s updated checklist item from %(old)s to %(new)s",
                            ),
                            (
                                "remove_checklist_item",
                                "%(user)s removed checklist item %(item)s",
                            ),
                            ("add_comment", "%(user)s added comment"),
                            ("update_comment", "%(user)s updated comment"),
                            ("remove_comment", "%(user)s removed comment"),
                            ("add_file", "%(user)s added a file"),
                            ("remove_file", "%(user)s removed a file"),
                            ("start_timer", "%(user)s started timer"),
                            (
                                "stop_timer",
                                "%(user)s stopped timer (logged duration: %(duration)s)",
                            ),
                            (
                                "update_time_entry",
                                "%(user)s updated a time entry (duration changed from %(old)s to %(new)s)",
                            ),
                            (
                                "delete_time_entry",
                                "%(user)s deleted a time entry",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("context", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="project_manager.card",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "activity",
                "verbose_name_plural": "activities",
            },
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("board", "name"), name="unique_tag"
            ),
        ),
    ]
