# Generated by Django 3.2.11 on 2022-01-25 16:46

import django.db.models.deletion
import project_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0001_squashed_0062_alter_card_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardfile",
            name="file",
            field=models.FileField(
                max_length=1000,
                upload_to=project_manager.models.CardFile._card_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="order",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="tag",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="project_manager.board",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="dark",
            field=models.CharField(max_length=7, verbose_name="dark"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="light",
            field=models.CharField(max_length=7, verbose_name="light"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="primary",
            field=models.CharField(max_length=7, verbose_name="primary"),
        ),
    ]
