# Generated by Django 3.2.4 on 2021-08-01 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_manager', '0003_auto_20210801_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
