# Generated by Django 3.2.4 on 2021-08-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0004_alter_card_assigned_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['bucket__board__project', 'bucket__board', 'bucket', 'order']},
        ),
        migrations.AddField(
            model_name='bucket',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
