# Generated by Django 3.2.13 on 2022-04-21 02:59

from django.db import migrations
from ..models import Icon, Theme


def create_default_icons_and_themes(*args, **kwargs):
    Icon.create_defaults()
    Theme.create_defaults()


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0004_alter_board_options'),
    ]

    operations = [
        migrations.RunPython(create_default_icons_and_themes)
    ]
