# Generated by Django 3.2.4 on 2021-08-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0006_auto_20210803_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
