# Generated by Django 3.2.13 on 2022-05-16 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0006_space"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="space",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project_manager.space",
            ),
        ),
    ]
