# Generated by Django 3.2.13 on 2022-05-17 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0007_board_space"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="project",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project_manager.project",
            ),
        ),
    ]
