# Generated by Django 3.2.4 on 2021-08-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0007_alter_timeentry_stopped_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentry',
            options={'verbose_name': 'time entry', 'verbose_name_plural': 'time entries'},
        ),
        migrations.AddField(
            model_name='timeentry',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
