# Generated by Django 3.2.13 on 2022-05-17 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0008_space_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="project_manager.project",
            ),
            preserve_default=False,
        ),
    ]
