# Generated by Django 3.2.4 on 2021-08-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0008_auto_20210803_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='duration',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
    ]
