# Generated by Django 3.2.13 on 2022-05-17 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0009_alter_space_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spaces",
                to="project_manager.project",
            ),
        ),
    ]
