# Generated by Django 3.2.13 on 2022-06-14 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0010_alter_space_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="space",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_manager.space",
            ),
        ),
    ]
