# Generated by Django 3.2.4 on 2021-08-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0011_bucket_auto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='auto_status',
            field=models.CharField(choices=[('N', 'No automatic status'), ('NS', 'Not started'), ('IP', 'In progress'), ('C', 'Completed')], default='N', max_length=2, verbose_name='status'),
        ),
    ]
