# Generated by Django 3.2.4 on 2021-08-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0012_alter_bucket_auto_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('active', models.BooleanField(default=True)),
                ('card_handle', models.CharField(blank=True, max_length=7, null=True, verbose_name='card handle')),
                ('card_content', models.CharField(blank=True, max_length=7, null=True, verbose_name='card content')),
                ('card_extra_content', models.CharField(blank=True, max_length=7, null=True, verbose_name='card extra content')),
            ],
        ),
    ]
