# Generated by Django 3.2.13 on 2022-07-04 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0013_auto_20220704_1700"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["-created_by"],
                "verbose_name": "activity",
                "verbose_name_plural": "activities",
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="card",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="project_manager.card",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="activity",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("deleted", "Deleted"),
                ],
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="type",
            field=models.CharField(
                choices=[
                    ("card", "Card"),
                    ("title", "Title"),
                    ("description", "Description"),
                ],
                max_length=20,
            ),
        ),
    ]
