# Generated by Django 3.2.4 on 2021-08-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0013_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='bucket_content',
            field=models.CharField(default=0, max_length=7, verbose_name='bucket content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='bucket_handle',
            field=models.CharField(default=1, max_length=7, verbose_name='bucket handle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theme',
            name='card_content',
            field=models.CharField(default=1, max_length=7, verbose_name='card content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theme',
            name='card_extra_content',
            field=models.CharField(default=1, max_length=7, verbose_name='card extra content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theme',
            name='card_handle',
            field=models.CharField(default=1, max_length=7, verbose_name='card handle'),
            preserve_default=False,
        ),
    ]
