# Generated by Django 3.2.13 on 2022-07-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0014_auto_20220704_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='type',
        ),
        migrations.AddField(
            model_name='activity',
            name='target',
            field=models.CharField(choices=[('card', 'Card'), ('name', 'Name'), ('description', 'Description'), ('tags', 'Tags'), ('checklist_item', 'Checklist item'), ('due_date', 'Due date'), ('status', 'Status'), ('assignees', 'Assignees'), ('file', 'File'), ('comment', 'Comment'), ('timer', 'Timer')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('start', 'Start'), ('stop', 'Stop')], max_length=7),
        ),
    ]
