# Generated by Django 3.2.4 on 2021-08-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0014_auto_20210805_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
    ]
