# Generated by Django 3.2.4 on 2021-08-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0015_alter_theme_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='bucket_content',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='bucket_handle',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='card_content',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='card_extra_content',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='card_handle',
        ),
        migrations.AddField(
            model_name='theme',
            name='primary',
            field=models.CharField(default=1, max_length=7, verbose_name='primary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='secondary',
            field=models.CharField(default=1, max_length=7, verbose_name='secondary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='tertiary',
            field=models.CharField(default=1, max_length=7, verbose_name='tertiary'),
            preserve_default=False,
        ),
    ]
