# Generated by Django 3.2.4 on 2021-08-05 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0017_card_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_manager.theme'),
        ),
    ]
