# Generated by Django 3.2.13 on 2022-07-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0018_set_uuid_fields_to_unique"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="target",
        ),
        migrations.AlterField(
            model_name="activity",
            name="action",
            field=models.CharField(
                choices=[
                    ("create_card", "Create Card"),
                    ("update_name", "Update Name"),
                    ("update_description", "Update Description"),
                    ("update_due_date", "Update Due Date"),
                    ("update_status", "Update Status"),
                    ("update_color", "Update Color"),
                    ("update_tags", "Update Tags"),
                    ("update_assignees", "Update Assignees"),
                    ("add_checklist_item", "Add Checklist Item"),
                    ("update_checklist_item", "Update Checklist Item"),
                    ("remove_checklist_item", "Remove Checklist Item"),
                    ("add_comment", "Add Comment"),
                    ("update_comment", "Update Comment"),
                    ("remove_comment", "Remove Comment"),
                    ("add_file", "Add File"),
                    ("remove_file", "Remove File"),
                    ("start_timer", "Start Timer"),
                    ("stop_timer", "Stop Timer"),
                ],
                max_length=100,
            ),
        ),
    ]
