# Generated by Django 3.2.4 on 2021-08-06 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_manager', '0019_auto_20210806_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
