# Generated by Django 3.2.4 on 2021-08-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0020_auto_20210806_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
