# Generated by Django 3.2.4 on 2021-08-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0021_alter_project_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['project', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created_at']},
        ),
    ]
