# Generated by Django 3.2.4 on 2021-08-06 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_manager', '0022_auto_20210806_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'icon',
                'verbose_name_plural': 'icons',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('read_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('action', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('active', models.BooleanField(default=True)),
                ('icon', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_manager.icon')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_manager_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
            },
        ),
    ]
