# Generated by Django 3.2.4 on 2021-08-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0023_icon_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='secondary',
        ),
        migrations.AddField(
            model_name='theme',
            name='dark',
            field=models.CharField(default=1, max_length=7, verbose_name='dark'),
            preserve_default=False,
        ),
    ]
