# Generated by Django 3.2.4 on 2021-08-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0024_auto_20210806_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='tertiary',
        ),
        migrations.AddField(
            model_name='theme',
            name='light',
            field=models.CharField(default=1, max_length=7, verbose_name='light'),
            preserve_default=False,
        ),
    ]
