# Generated by Django 3.2.4 on 2021-08-12 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0028_alter_card_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_manager.project'),
        ),
    ]
