# Generated by Django 3.2.4 on 2021-08-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0029_alter_invite_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
