# Generated by Django 3.2.5 on 2021-08-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0030_alter_timeentry_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='compact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='board',
            name='fullscreen',
            field=models.BooleanField(default=False),
        ),
    ]
