# Generated by Django 3.2.5 on 2021-08-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0031_auto_20210814_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='bucket_width',
            field=models.IntegerField(default=300),
        ),
    ]
