# Generated by Django 3.2.5 on 2021-08-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0032_board_bucket_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='dark',
            field=models.BooleanField(default=False),
        ),
    ]
