# Generated by Django 3.2.4 on 2021-08-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0033_board_dark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['card__bucket__board__project', 'card__bucket__board', 'card__bucket', 'card', 'order']},
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
