# Generated by Django 3.2.4 on 2021-08-16 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_manager', '0034_auto_20210816_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': []},
        ),
        migrations.AlterField(
            model_name='item',
            name='checked_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='checked_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
