# Generated by Django 3.2.4 on 2021-08-16 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0035_auto_20210816_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['order']},
        ),
    ]
