# Generated by Django 3.2.4 on 2021-08-18 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0038_alter_tag_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_manager.board'),
            preserve_default=False,
        ),
    ]
