# Generated by Django 3.2.4 on 2021-08-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0039_tag_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='tag',
            field=models.ManyToManyField(blank=True, to='project_manager.Tag'),
        ),
    ]
