# Generated by Django 3.2.4 on 2021-08-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0041_alter_card_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='tag',
            field=models.ManyToManyField(blank=True, default=None, to='project_manager.Tag'),
        ),
    ]
