# Generated by Django 3.2.4 on 2021-08-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0045_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
