# Generated by Django 3.2.4 on 2021-08-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0046_auto_20210820_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_by']},
        ),
    ]
