# Generated by Django 3.2.4 on 2021-08-20 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0047_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
