# Generated by Django 3.2.4 on 2021-09-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0049_alter_timeentry_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
