# Generated by Django 3.2.4 on 2021-09-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0050_card_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
