# Generated by Django 3.2.7 on 2021-09-09 16:19

import django.db.models.deletion
import project_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0053_board_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='files',
        ),
        migrations.CreateModel(
            name='CardFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=1000, null=True, upload_to=project_manager.models.CardFile._card_directory_path)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.card')),
            ],
        ),
    ]
