# Generated by Django 3.2.7 on 2021-09-09 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0054_auto_20210909_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardfile',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project_manager.card'),
        ),
    ]
