# Generated by Django 3.2.7 on 2021-10-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0056_alter_cardfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='assignees_feature',
            field=models.BooleanField(default=True, help_text='Enables assignees on cards'),
        ),
        migrations.AddField(
            model_name='board',
            name='checklist_feature',
            field=models.BooleanField(default=True, help_text='Enables checklist on cards'),
        ),
        migrations.AddField(
            model_name='board',
            name='color_feature',
            field=models.BooleanField(default=True, help_text='Enables color on cards'),
        ),
        migrations.AddField(
            model_name='board',
            name='comments_feature',
            field=models.BooleanField(default=True, help_text='Enables users to comment on cards'),
        ),
        migrations.AddField(
            model_name='board',
            name='due_date_feature',
            field=models.BooleanField(default=True, help_text='Enables cards to have due dates'),
        ),
        migrations.AddField(
            model_name='board',
            name='files_feature',
            field=models.BooleanField(default=True, help_text='Enables file attachments on cards'),
        ),
        migrations.AddField(
            model_name='board',
            name='status_feature',
            field=models.BooleanField(default=True, help_text='Enables status on cards'),
        ),
        migrations.AddField(
            model_name='board',
            name='tags_feature',
            field=models.BooleanField(default=True, help_text='Enables taga on cards'),
        ),
    ]
