# Generated by Django 3.2.9 on 2021-11-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0059_delete_notification'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invite',
            constraint=models.UniqueConstraint(fields=('email', 'project'), name='unique_email_by_project'),
        ),
    ]
