# Generated by Django 3.2.9 on 2021-11-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0060_invite_unique_email_by_project'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invite',
            name='unique_email_by_project',
        ),
    ]
