# Generated by Django 3.2.9 on 2021-11-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0061_remove_invite_unique_email_by_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
