# Generated by Django 4.2.5 on 2023-09-20 19:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from __mono.fields import MultiSelectField
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("initial_balance", models.FloatField(default=0)),
                ("credit_card", models.BooleanField(default=False)),
                (
                    "settlement_date",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(28),
                        ],
                    ),
                ),
                (
                    "due_date",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(28),
                        ],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_accountset",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "account",
                "verbose_name_plural": "accounts",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "description",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("EXP", "Expense"), ("INC", "Income")],
                        default="EXP",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "internal_type",
                    models.CharField(
                        choices=[
                            ("DEF", "Default"),
                            ("TRF", "Transfer"),
                            ("ADJ", "Balance adjustment"),
                        ],
                        default="DEF",
                        max_length=3,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_groupset",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="shared_groupset",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_groupset",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "group",
                "verbose_name_plural": "groups",
            },
        ),
        migrations.CreateModel(
            name="Icon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("markup", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "icon",
                "verbose_name_plural": "icons",
            },
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "months",
                    models.IntegerField(default=12, verbose_name="months"),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="A short description, so that the user can identify the transaction.",
                        max_length=50,
                        verbose_name="description",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when transaction occurred. User defined.",
                        verbose_name="timestamp",
                    ),
                ),
                (
                    "total_amount",
                    models.FloatField(
                        help_text="Amount related to the transaction. Absolute value, no positive/negative signs.",
                        verbose_name="total amount",
                    ),
                ),
                (
                    "handle_remainder",
                    models.CharField(
                        choices=[
                            ("F", "Add to first transaction"),
                            ("L", "Add to last transaction"),
                        ],
                        default="F",
                        max_length=1,
                        verbose_name="handle remainder",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.account",
                        verbose_name="account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "installment",
                "verbose_name_plural": "installments",
            },
        ),
        migrations.CreateModel(
            name="RecurrentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="A short description, so that the user can identify the transaction.",
                        max_length=50,
                        verbose_name="description",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when transaction occurred. User defined.",
                        verbose_name="timestamp",
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        help_text="Amount related to the transaction. Absolute value, no positive/negative signs.",
                        verbose_name="amount",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="active"),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("W", "Weekly"),
                            ("M", "Monthly"),
                            ("Y", "Yearly"),
                        ],
                        default="M",
                        max_length=1,
                        verbose_name="frequency",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.account",
                        verbose_name="account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Identifies who created the transaction.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "recurrent transaction",
                "verbose_name_plural": "recurrent transactions",
            },
        ),
        migrations.CreateModel(
            name="Transference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        default="Transfer",
                        help_text="A short description, so that the user can identify the transaction.",
                        max_length=50,
                        verbose_name="description",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when transaction occurred. User defined.",
                        verbose_name="timestamp",
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        help_text="Amount related to the transaction. Absolute value, no positive/negative signs.",
                        verbose_name="amount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Identifies who created the transaction.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "from_account",
                    models.ForeignKey(
                        help_text="Source account in which an expense will be stored.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_transferences",
                        to="finance.account",
                        verbose_name="from account",
                    ),
                ),
                (
                    "to_account",
                    models.ForeignKey(
                        help_text="Destination account in which an income will be stored.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_transferences",
                        to="finance.account",
                        verbose_name="to account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="A short description, so that the user can identify the transaction.",
                        max_length=50,
                        verbose_name="description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created at"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when transaction occurred. User defined.",
                        verbose_name="timestamp",
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        help_text="Amount related to the transaction. Absolute value, no positive/negative signs.",
                        verbose_name="amount",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="active"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.account",
                        verbose_name="account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Identifies who created the transaction.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "installment",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.installment",
                        verbose_name="installment",
                    ),
                ),
                (
                    "recurrent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.recurrenttransaction",
                    ),
                ),
                (
                    "transference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.transference",
                        verbose_name="installment",
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction",
                "verbose_name_plural": "transactions",
            },
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("email", models.EmailField(max_length=1000)),
                (
                    "accepted",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "invite",
                "verbose_name_plural": "invites",
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("target_date", models.DateField()),
                ("target_amount", models.FloatField()),
                (
                    "progression_mode",
                    models.CharField(
                        choices=[("C", "Constant"), ("L", "Linear")],
                        default="C",
                        max_length=1,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("W", "Weekly"),
                            ("M", "Monthly"),
                            ("Y", "Yearly"),
                        ],
                        default="M",
                        editable=False,
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "goal",
                "verbose_name_plural": "goals",
            },
        ),
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_page",
                    models.CharField(
                        choices=[
                            ("HOM", "Home"),
                            ("ACC", "Accounts"),
                            ("TRN", "Transactions"),
                            ("GRP", "Groups"),
                            ("CTG", "Categories"),
                            ("GOL", "Goals"),
                        ],
                        default="HOM",
                        max_length=3,
                    ),
                ),
                (
                    "cards",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Used to store comma-separated string of integers             corresponding to cards",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "configuration",
                "verbose_name_plural": "configurations",
            },
        ),
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bar", "Bar"),
                            ("line", "Line"),
                            ("column", "Column"),
                            ("donut", "Donut"),
                        ],
                        default="bar",
                        max_length=100,
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("count", "Count"),
                            ("sum", "Sum"),
                            ("avg", "Average"),
                        ],
                        default="sum",
                        max_length=100,
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("transaction", "Transaction"),
                            ("transference", "Transference"),
                            ("recurrent_transaction", "Recurrent Transaction"),
                            ("installment", "Installment"),
                        ],
                        default="transaction",
                        max_length=100,
                    ),
                ),
                (
                    "axis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("year", "Year"),
                            ("month", "Month"),
                            ("week", "Week"),
                        ],
                        default="month",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[("category", "Category"), ("type", "Type")],
                        default="category",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "filters",
                    MultiSelectField(
                        blank=True,
                        choices=[
                            ("expenses", "Expenses"),
                            ("incomes", "Incomes"),
                            ("balance_adjustments", "Balance adjustments"),
                            (
                                "not_balance_adjustments",
                                "Not balance adjustments",
                            ),
                            ("transferences", "Transferences"),
                            ("not_transferences", "Not transferences"),
                            ("current_year", "Current year"),
                            ("past_year", "Past year"),
                            ("current_month", "Current month"),
                            ("past_month", "Past month"),
                        ],
                        default=None,
                        max_length=140,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(default="Untitled chart", max_length=100),
                ),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_by", "order"],
            },
        ),
        migrations.AddField(
            model_name="category",
            name="group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.group",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finance.icon",
            ),
        ),
        migrations.CreateModel(
            name="BudgetConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("start_date", models.DateField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("W", "Weekly"),
                            ("M", "Monthly"),
                            ("Y", "Yearly"),
                        ],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "all_accounts",
                    models.BooleanField(
                        default=False, verbose_name="all accounts"
                    ),
                ),
                (
                    "all_categories",
                    models.BooleanField(
                        default=False, verbose_name="all categories"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("accounts", models.ManyToManyField(to="finance.account")),
                ("categories", models.ManyToManyField(to="finance.category")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "budget configuration",
                "verbose_name_plural": "budget configurations",
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(verbose_name="amount")),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="start date",
                    ),
                ),
                ("end_date", models.DateField(verbose_name="end date")),
                (
                    "all_accounts",
                    models.BooleanField(
                        default=False, verbose_name="all accounts"
                    ),
                ),
                (
                    "all_categories",
                    models.BooleanField(
                        default=False, verbose_name="all categories"
                    ),
                ),
                (
                    "accounts",
                    models.ManyToManyField(
                        to="finance.account", verbose_name="accounts"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        to="finance.category", verbose_name="categories"
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.budgetconfiguration",
                        verbose_name="configuration",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "budget",
                "verbose_name_plural": "budgets",
            },
        ),
        migrations.AddField(
            model_name="account",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finance.group",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="owned_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_accountset",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
