# Generated by Django 3.2.11 on 2022-01-25 16:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from __mono.fields import MultiSelectField
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("finance", "0001_initial"),
        ("finance", "0002_budget_goal"),
        ("finance", "0003_goal_name"),
        ("finance", "0004_invite"),
        ("finance", "0005_invite_accepted"),
        ("finance", "0006_auto_20210302_1848"),
        ("finance", "0007_auto_20210302_1850"),
        ("finance", "0008_auto_20210308_1016"),
        ("finance", "0009_auto_20210308_1150"),
        ("finance", "0010_auto_20210309_1418"),
        ("finance", "0011_notification"),
        ("finance", "0012_auto_20210310_1719"),
        ("finance", "0013_configuration"),
        ("finance", "0014_auto_20210311_1732"),
        ("finance", "0015_auto_20210313_2257"),
        ("finance", "0016_auto_20210315_1442"),
        ("finance", "0017_auto_20210315_1451"),
        ("finance", "0018_budget_created_by"),
        ("finance", "0019_auto_20210318_1115"),
        ("finance", "0020_auto_20210318_1202"),
        ("finance", "0021_auto_20210323_1755"),
        ("finance", "0022_feature_plan"),
        ("finance", "0023_auto_20210325_1106"),
        ("finance", "0024_plan_icon"),
        ("finance", "0025_subscription"),
        ("finance", "0026_subscription_cancel_at"),
        ("finance", "0027_plan_order"),
        ("finance", "0028_auto_20210326_1640"),
        ("finance", "0029_auto_20210326_1805"),
        (
            "finance",
            "0030_budgetconfiguration_data_squashed_0032_auto_20210329_1547",
        ),
        ("finance", "0031_auto_20210329_1720"),
        ("finance", "0032_auto_20210330_1646"),
        ("finance", "0033_auto_20210331_1528"),
        ("finance", "0034_auto_20210401_1015"),
        ("finance", "0035_auto_20210401_1036"),
        ("finance", "0036_auto_20210401_1424"),
        ("finance", "0037_auto_20210401_1425"),
        ("finance", "0038_auto_20210405_1159"),
        ("finance", "0039_configuration_cards"),
        ("finance", "0040_auto_20210409_1409"),
        ("finance", "0041_auto_20210413_1749"),
        ("finance", "0042_auto_20210414_1611"),
        ("finance", "0043_auto_20210414_1823"),
        ("finance", "0044_auto_20210422_1656"),
        ("finance", "0045_auto_20210426_0832"),
        ("finance", "0046_auto_20211002_1952"),
        ("finance", "0047_auto_20211003_0048"),
        ("finance", "0048_auto_20211003_0053"),
        ("finance", "0049_auto_20211003_0100"),
        ("finance", "0050_rename_closing_date_account_settlement_date"),
        ("finance", "0051_account_due_date"),
        ("finance", "0052_auto_20211008_0023"),
        ("finance", "0053_alter_category_type"),
        ("finance", "0054_alter_recurrenttransaction_options"),
        ("finance", "0055_alter_recurrenttransaction_options"),
        ("finance", "0056_delete_notification"),
        ("finance", "0057_chart"),
        ("finance", "0058_auto_20211201_2204"),
        ("finance", "0059_chart_filters"),
        ("finance", "0060_auto_20211213_1617"),
        ("finance", "0061_auto_20211213_1624"),
        ("finance", "0062_alter_chart_type"),
        ("finance", "0063_alter_chart_axis"),
        ("finance", "0064_auto_20211215_0911"),
        ("finance", "0065_alter_chart_options"),
        ("finance", "0066_auto_20220120_1639"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Icon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("markup", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "icon",
                "verbose_name_plural": "icons",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="shared_groupset",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_groupset",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owned_by",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_groupset",
                        to="auth.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "group",
                "verbose_name_plural": "groups",
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("initial_balance", models.FloatField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.group",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_accountset",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owned_by",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_accountset",
                        to="auth.user",
                    ),
                ),
                (
                    "settlement_date",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(28),
                        ],
                    ),
                ),
                ("credit_card", models.BooleanField(default=False)),
                (
                    "due_date",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(28),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "account",
                "verbose_name_plural": "accounts",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "description",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("EXP", "Expense"), ("INC", "Income")],
                        default="EXP",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.group",
                    ),
                ),
                (
                    "icon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.icon",
                    ),
                ),
                (
                    "internal_type",
                    models.CharField(
                        choices=[
                            ("DEF", "Default"),
                            ("TRF", "Transfer"),
                            ("ADJ", "Balance adjustment"),
                        ],
                        default="DEF",
                        max_length=3,
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="BudgetConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("W", "Weekly"),
                            ("M", "Monthly"),
                            ("Y", "Yearly"),
                        ],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("accounts", models.ManyToManyField(to="finance.Account")),
                ("categories", models.ManyToManyField(to="finance.Category")),
                ("start_date", models.DateField()),
                (
                    "all_accounts",
                    models.BooleanField(
                        default=False, verbose_name="all accounts"
                    ),
                ),
                (
                    "all_categories",
                    models.BooleanField(
                        default=False, verbose_name="all categories"
                    ),
                ),
            ],
            options={
                "verbose_name": "budget configuration",
                "verbose_name_plural": "budget configurations",
            },
        ),
        migrations.CreateModel(
            name="RecurrentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="A short description, so that the user can identify the transaction.",
                        max_length=50,
                        verbose_name="description",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when transaction occurred. User defined.",
                        verbose_name="timestamp",
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        help_text="Amount related to the transaction. Absolute value, no positive/negative signs.",
                        verbose_name="amount",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="active"),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("W", "Weekly"),
                            ("M", "Monthly"),
                            ("Y", "Yearly"),
                        ],
                        default="M",
                        max_length=1,
                        verbose_name="frequency",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.account",
                        verbose_name="account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Identifies who created the transaction.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "recurrent transaction",
                "verbose_name_plural": "recurrent transactions",
            },
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "months",
                    models.IntegerField(default=12, verbose_name="months"),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="A short description, so that the user can identify the transaction.",
                        max_length=50,
                        verbose_name="description",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when transaction occurred. User defined.",
                        verbose_name="timestamp",
                    ),
                ),
                (
                    "total_amount",
                    models.FloatField(
                        help_text="Amount related to the transaction. Absolute value, no positive/negative signs.",
                        verbose_name="total amount",
                    ),
                ),
                (
                    "handle_remainder",
                    models.CharField(
                        choices=[
                            ("F", "Add to first transaction"),
                            ("L", "Add to last transaction"),
                        ],
                        default="F",
                        max_length=1,
                        verbose_name="handle remainder",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.account",
                        verbose_name="account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "installment",
                "verbose_name_plural": "installments",
            },
        ),
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_page",
                    models.CharField(
                        choices=[
                            ("HOM", "Home"),
                            ("ACC", "Accounts"),
                            ("TRN", "Transactions"),
                            ("GRP", "Groups"),
                            ("CTG", "Categories"),
                            ("GOL", "Goals"),
                        ],
                        default="HOM",
                        max_length=3,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cards",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Used to store comma-separated string of integers             corresponding to cards",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "configuration",
                "verbose_name_plural": "configurations",
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("target_date", models.DateField()),
                ("target_amount", models.FloatField()),
                (
                    "progression_mode",
                    models.CharField(
                        choices=[("C", "Constant"), ("L", "Linear")],
                        default="C",
                        max_length=1,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("W", "Weekly"),
                            ("M", "Monthly"),
                            ("Y", "Yearly"),
                        ],
                        default="M",
                        editable=False,
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.group",
                    ),
                ),
                ("name", models.CharField(default=0, max_length=50)),
            ],
            options={
                "verbose_name": "goal",
                "verbose_name_plural": "goals",
            },
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("email", models.EmailField(max_length=1000)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.group",
                    ),
                ),
                (
                    "accepted",
                    models.BooleanField(default=False, editable=False),
                ),
            ],
            options={
                "verbose_name": "invite",
                "verbose_name_plural": "invites",
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(verbose_name="amount")),
                ("end_date", models.DateField(verbose_name="end date")),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="start date",
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.budgetconfiguration",
                        verbose_name="configuration",
                    ),
                ),
                (
                    "accounts",
                    models.ManyToManyField(
                        to="finance.Account", verbose_name="accounts"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        to="finance.Category", verbose_name="categories"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.user",
                    ),
                ),
                (
                    "all_accounts",
                    models.BooleanField(
                        default=False, verbose_name="all accounts"
                    ),
                ),
                (
                    "all_categories",
                    models.BooleanField(
                        default=False, verbose_name="all categories"
                    ),
                ),
            ],
            options={
                "verbose_name": "budget",
                "verbose_name_plural": "budgets",
            },
        ),
        migrations.CreateModel(
            name="Transference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        default="Transfer",
                        help_text="A short description, so that the user can identify the transaction.",
                        max_length=50,
                        verbose_name="description",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when transaction occurred. User defined.",
                        verbose_name="timestamp",
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        help_text="Amount related to the transaction. Absolute value, no positive/negative signs.",
                        verbose_name="amount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Identifies who created the transaction.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "from_account",
                    models.ForeignKey(
                        help_text="Source account in which an expense will be stored.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_transferences",
                        to="finance.account",
                        verbose_name="from account",
                    ),
                ),
                (
                    "to_account",
                    models.ForeignKey(
                        help_text="Destination account in which an income will be stored.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_transferences",
                        to="finance.account",
                        verbose_name="to account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="A short description, so that the user can identify the transaction.",
                        max_length=50,
                        verbose_name="description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created at"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when transaction occurred. User defined.",
                        verbose_name="timestamp",
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        help_text="Amount related to the transaction. Absolute value, no positive/negative signs.",
                        verbose_name="amount",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="active"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.account",
                        verbose_name="account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Identifies who created the transaction.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "recurrent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.recurrenttransaction",
                    ),
                ),
                (
                    "installment",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.installment",
                        verbose_name="installment",
                    ),
                ),
                (
                    "transference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.transference",
                        verbose_name="installment",
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction",
                "verbose_name_plural": "transactions",
            },
        ),
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bar", "Bar"),
                            ("line", "Line"),
                            ("column", "Column"),
                            ("donut", "Donut"),
                        ],
                        default="bar",
                        max_length=100,
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("count", "Count"),
                            ("sum", "Sum"),
                            ("avg", "Average"),
                        ],
                        default="sum",
                        max_length=100,
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("transaction", "Transaction"),
                            ("transference", "Transference"),
                            ("recurrent_transaction", "Recurrent Transaction"),
                            ("installment", "Installment"),
                        ],
                        default="transaction",
                        max_length=100,
                    ),
                ),
                (
                    "axis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("year", "Year"),
                            ("month", "Month"),
                            ("week", "Week"),
                        ],
                        default="month",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[("category", "Category"), ("type", "Type")],
                        default="category",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "filters",
                    MultiSelectField(
                        blank=True,
                        choices=[
                            ("expenses", "Expenses"),
                            ("incomes", "Incomes"),
                            ("balance_adjustments", "Balance adjustments"),
                            (
                                "not_balance_adjustments",
                                "Not balance adjustments",
                            ),
                            ("transferences", "Transferences"),
                            ("not_transferences", "Not transferences"),
                            ("current_year", "Current year"),
                            ("past_year", "Past year"),
                            ("current_month", "Current month"),
                            ("past_month", "Past month"),
                        ],
                        default=None,
                        max_length=140,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charts",
                        to="auth.user",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "title",
                    models.CharField(default="Untitled chart", max_length=100),
                ),
            ],
            options={
                "ordering": ["created_by", "order"],
            },
        ),
    ]
