# Generated by Django 3.1.6 on 2021-02-15 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_account_belongs_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='value',
            new_name='ammount',
        ),
    ]
