# Generated by Django 3.1.6 on 2021-03-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_invite_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
