# Generated by Django 3.1.6 on 2021-02-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_transaction_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('INC', 'Income'), ('EXP', 'Expense')], default='EXP', max_length=3),
        ),
    ]
