# Generated by Django 3.1.6 on 2021-02-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='initial_balance',
            field=models.FloatField(default=0),
        ),
    ]
