# Generated by Django 3.1.6 on 2021-03-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20210302_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='accepted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
