# Generated by Django 3.1.6 on 2021-03-08 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0008_auto_20210308_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='owned_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_groupset', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groupset', to=settings.AUTH_USER_MODEL),
        ),
    ]
