# Generated by Django 3.1.6 on 2021-02-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20210217_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='member',
            new_name='members',
        ),
    ]
