# Generated by Django 3.1.7 on 2021-03-11 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0012_auto_20210310_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_page', models.CharField(choices=[('HOM', 'Home'), ('ACC', 'Accounts'), ('TRN', 'Transactions'), ('GRP', 'Groups'), ('CTG', 'Categories'), ('GOL', 'Goals')], default='HOM', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
