# Generated by Django 3.1.7 on 2021-03-14 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_auto_20210311_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='category',
            name='internal_type',
            field=models.CharField(choices=[('DEF', 'Default'), ('TRF', 'Transfer'), ('ADJ', 'Balance adjustment')], default='DEF', max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.group'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.category'),
            preserve_default=False,
        ),
    ]
