# Generated by Django 3.1.7 on 2021-03-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_auto_20210315_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='accounts',
            field=models.ManyToManyField(to='finance.Account'),
        ),
        migrations.AddField(
            model_name='budget',
            name='categories',
            field=models.ManyToManyField(to='finance.Category'),
        ),
        migrations.AddField(
            model_name='budgetconfiguration',
            name='accounts',
            field=models.ManyToManyField(to='finance.Account'),
        ),
        migrations.AddField(
            model_name='budgetconfiguration',
            name='categories',
            field=models.ManyToManyField(to='finance.Category'),
        ),
    ]
