# Generated by Django 3.1.7 on 2021-03-18 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_auto_20210318_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when transaction occurred. User defined.'),
        ),
    ]
