# Generated by Django 3.1.7 on 2021-03-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_feature_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='full_description',
            field=models.TextField(max_length=200),
        ),
    ]
