# Generated by Django 3.1.7 on 2021-03-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancel_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
