# Generated by Django 3.1.7 on 2021-03-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_subscription_cancel_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='order',
            field=models.IntegerField(default=0, help_text='Used to sort plans on the template.'),
            preserve_default=False,
        ),
    ]
