# Generated by Django 3.1.7 on 2021-03-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_plan_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='order',
            field=models.IntegerField(help_text='Used to sort plans on the template.', unique=True),
        ),
    ]
