# Generated by Django 3.1.7 on 2021-03-26 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_auto_20210326_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['order']},
        ),
    ]
