# Generated by Django 3.1.7 on 2021-03-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('finance', '0030_budgetconfiguration_data'), ('finance', '0031_auto_20210329_1150'), ('finance', '0032_auto_20210329_1547')]

    dependencies = [
        ('finance', '0029_auto_20210326_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetconfiguration',
            name='start_date',
            field=models.IntegerField(default=1),
        ),
    ]
