# Generated by Django 3.1.7 on 2021-03-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_auto_20210326_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetconfiguration',
            name='data',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
