# Generated by Django 3.1.7 on 2021-03-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_budgetconfiguration_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetconfiguration',
            old_name='data',
            new_name='date',
        ),
    ]
