# Generated by Django 3.1.7 on 2021-03-29 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_auto_20210329_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetconfiguration',
            old_name='date',
            new_name='start_date',
        ),
    ]
