# Generated by Django 3.1.7 on 2021-03-31 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0032_auto_20210330_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='A short description, so that the user can identify the transaction.', max_length=50, verbose_name='description')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when transaction occurred. User defined.', verbose_name='timestamp')),
                ('ammount', models.FloatField(help_text='Ammount related to the transaction. Absolute value, no positive/negative signs.', verbose_name='ammount')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('frequency', models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], default='M', max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account', verbose_name='account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.category', verbose_name='category')),
                ('created_by', models.ForeignKey(help_text='Identifies who created the transaction.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurrent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.recurrenttransaction'),
        ),
    ]
