# Generated by Django 3.1.7 on 2021-04-01 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0033_auto_20210331_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='ammount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='budgetconfiguration',
            old_name='ammount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='target_ammount',
            new_name='target_amount',
        ),
        migrations.RenameField(
            model_name='recurrenttransaction',
            old_name='ammount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='ammount',
            new_name='amount',
        ),
    ]
