# Generated by Django 3.1.7 on 2021-04-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0034_auto_20210401_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrenttransaction',
            name='amount',
            field=models.FloatField(help_text='Amount related to the transaction. Absolute value, no positive/negative signs.', verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(help_text='Amount related to the transaction. Absolute value, no positive/negative signs.', verbose_name='amount'),
        ),
    ]
