# Generated by Django 3.1.7 on 2021-04-01 17:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0035_auto_20210401_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.IntegerField(max_length=100)),
                ('description', models.CharField(help_text='A short description, so that the user can identify the transaction.', max_length=50, verbose_name='description')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when transaction occurred. User defined.', verbose_name='timestamp')),
                ('total_amount', models.FloatField(help_text='Amount related to the transaction. Absolute value, no positive/negative signs.', verbose_name='total amount')),
                ('handle_remainder', models.CharField(choices=[('F', 'Add to first transaction'), ('L', 'Add to last transaction')], default='F', max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account', verbose_name='account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.category', verbose_name='category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.installment', verbose_name='installment'),
        ),
    ]
