# Generated by Django 3.1.7 on 2021-04-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0036_auto_20210401_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='months',
            field=models.IntegerField(default=12),
        ),
    ]
