# Generated by Django 3.1.7 on 2021-04-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0037_auto_20210401_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
