# Generated by Django 3.1.7 on 2021-04-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0038_auto_20210405_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='cards',
            field=models.CharField(blank=True, default=None, help_text='Used to store comma-separated string of integers             corresponding to cards', max_length=100, null=True),
        ),
    ]
