# Generated by Django 3.2 on 2021-04-13 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0040_auto_20210409_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'budget', 'verbose_name_plural': 'budgets'},
        ),
        migrations.AlterModelOptions(
            name='budgetconfiguration',
            options={'verbose_name': 'budget configuration', 'verbose_name_plural': 'budget configurations'},
        ),
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name': 'configuration', 'verbose_name_plural': 'configurations'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'feature', 'verbose_name_plural': 'features'},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': 'goal', 'verbose_name_plural': 'goals'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
        migrations.AlterModelOptions(
            name='installment',
            options={'verbose_name': 'installment', 'verbose_name_plural': 'installments'},
        ),
        migrations.AlterModelOptions(
            name='invite',
            options={'verbose_name': 'invite', 'verbose_name_plural': 'invites'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['order'], 'verbose_name': 'plan', 'verbose_name_plural': 'plans'},
        ),
        migrations.AlterModelOptions(
            name='recurrenttransaction',
            options={'verbose_name': 'recurrent transaction', 'verbose_name_plural': 'recurrent transactions'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'subscription', 'verbose_name_plural': 'subscriptions'},
        ),
    ]
