# Generated by Django 3.2 on 2021-04-14 21:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0042_auto_20210414_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='accounts',
            field=models.ManyToManyField(to='finance.Account', verbose_name='accounts'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.FloatField(verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='categories',
            field=models.ManyToManyField(to='finance.Category', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.budgetconfiguration', verbose_name='configuration'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='start date'),
        ),
    ]
