# Generated by Django 3.2 on 2021-04-26 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0044_auto_20210422_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Transfer', help_text='A short description, so that the user can identify the transaction.', max_length=50, verbose_name='description')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when transaction occurred. User defined.', verbose_name='timestamp')),
                ('amount', models.FloatField(help_text='Amount related to the transaction. Absolute value, no positive/negative signs.', verbose_name='amount')),
                ('created_by', models.ForeignKey(help_text='Identifies who created the transaction.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('from_account', models.ForeignKey(help_text='Source account in which an expense will be stored.', on_delete=django.db.models.deletion.CASCADE, related_name='expense_transferences', to='finance.account', verbose_name='from account')),
                ('to_account', models.ForeignKey(help_text='Destination account in which an income will be stored.', on_delete=django.db.models.deletion.CASCADE, related_name='income_transferences', to='finance.account', verbose_name='to account')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transference',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.transference', verbose_name='installment'),
        ),
    ]
