# Generated by Django 3.2.7 on 2021-10-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0045_auto_20210426_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='closing_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='credit_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
