# Generated by Django 3.2.7 on 2021-10-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0046_auto_20211002_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='closing_date',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='due_date',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
