# Generated by Django 3.2.7 on 2021-10-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0047_auto_20211003_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='closing_date',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='due_date',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
