# Generated by Django 3.2.7 on 2021-10-03 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0048_auto_20211003_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='account',
            name='closing_date',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
    ]
