# Generated by Django 3.2.7 on 2021-10-04 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0050_rename_closing_date_account_settlement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='due_date',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
    ]
