# Generated by Django 3.2.9 on 2021-11-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0052_auto_20211008_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('EXP', 'Expense'), ('INC', 'Income')], default='EXP', max_length=3),
        ),
    ]
