# Generated by Django 3.2.9 on 2021-11-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0053_alter_category_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurrenttransaction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'recurrent transaction', 'verbose_name_plural': 'recurrent transactions'},
        ),
    ]
