# Generated by Django 3.2.9 on 2021-11-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0054_alter_recurrenttransaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurrenttransaction',
            options={'verbose_name': 'recurrent transaction', 'verbose_name_plural': 'recurrent transactions'},
        ),
    ]
