# Generated by Django 3.2.9 on 2021-11-24 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0055_alter_recurrenttransaction_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
