# Generated by Django 3.2.9 on 2021-12-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0057_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='axis',
            field=models.CharField(choices=[('year', 'Year'), ('month', 'Month'), ('week', 'Week')], default='month', max_length=100),
        ),
        migrations.AlterField(
            model_name='chart',
            name='category',
            field=models.CharField(choices=[('none', 'None'), ('category', 'Category'), ('type', 'Type')], default='category', max_length=100),
        ),
        migrations.AlterField(
            model_name='chart',
            name='field',
            field=models.CharField(choices=[('transaction', 'Transaction'), ('transference', 'Transference'), ('recurrent_transaction', 'Recurrent Transaction'), ('installment', 'Installment')], default='transaction', max_length=100),
        ),
        migrations.AlterField(
            model_name='chart',
            name='metric',
            field=models.CharField(choices=[('count', 'Count'), ('sum', 'Sum'), ('avg', 'Average')], default='sum', max_length=100),
        ),
        migrations.AlterField(
            model_name='chart',
            name='type',
            field=models.CharField(choices=[('bar', 'Bar'), ('line', 'Line'), ('column', 'Column')], default='bar', max_length=100),
        ),
    ]
