# Generated by Django 3.2.10 on 2021-12-07 12:32

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0058_auto_20211201_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='filters',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('none', 'None'), ('category', 'Category'), ('type', 'Type')], default=None, max_length=18, null=True),
        ),
    ]
