# Generated by Django 3.2.10 on 2021-12-13 16:24

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0060_auto_20211213_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='category',
            field=models.CharField(blank=True, choices=[('category', 'Category'), ('type', 'Type')], default='category', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='filters',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('expenses', 'Expenses'), ('incomes', 'Incomes'), ('balance_adjustments', 'Balance adjustments'), ('not_balance_adjustments', 'Not balance adjustments'), ('transferences', 'Transferences'), ('not_transferences', 'Not transferences'), ('current_year', 'Current year'), ('past_year', 'Past year'), ('current_month', 'Current month'), ('past_month', 'Past month')], default=None, max_length=140, null=True),
        ),
    ]
