# Generated by Django 3.2.10 on 2021-12-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0062_alter_chart_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='axis',
            field=models.CharField(blank=True, choices=[('year', 'Year'), ('month', 'Month'), ('week', 'Week')], default='month', max_length=100, null=True),
        ),
    ]
