# Generated by Django 3.2.10 on 2021-12-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0063_alter_chart_axis'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chart',
            name='title',
            field=models.CharField(default='Untitled chart', max_length=100),
        ),
    ]
