# Generated by Django 3.2.10 on 2021-12-24 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0064_auto_20211215_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chart',
            options={'ordering': ['created_by', 'order']},
        ),
    ]
