# Generated by Django 3.2.11 on 2022-01-25 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('watcher', '0001_initial'), ('watcher', '0002_alter_event_timestamp'), ('watcher', '0003_alter_traceback_code_text'), ('watcher', '0004_alter_traceback_options'), ('watcher', '0005_auto_20211005_1944'), ('watcher', '0006_auto_20211009_0037'), ('watcher', '0007_alter_issue_options')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL)),
                ('ignored_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('ignored_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ignored_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watcher.issue')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Traceback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('file_name', models.CharField(max_length=1000)),
                ('function_name', models.CharField(max_length=1000)),
                ('line_number', models.PositiveIntegerField()),
                ('code_text', models.JSONField()),
                ('variables', models.JSONField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watcher.issue')),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
    ]
