# Generated by Django 3.2.11 on 2022-01-31 20:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("watcher", "0001_squashed_0007_alter_issue_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("duration", models.DurationField()),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=2000)),
                (
                    "route",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                (
                    "url_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "app_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
