# Generated by Django 3.2.11 on 2022-02-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0002_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='route',
            field=models.CharField(blank=True, help_text='URL pattern', max_length=2000, null=True),
        ),
    ]
