# Generated by Django 4.1.1 on 2022-10-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watcher", "0004_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="app_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
    ]
