# Generated by Django 4.1.1 on 2022-10-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watcher", "0005_alter_request_app_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="started_at",
            field=models.DateTimeField(),
        ),
    ]
