# Generated by Django 3.2.7 on 2021-10-20 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0006_auto_20211009_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at']},
        ),
    ]
