# Generated by Django 4.1.1 on 2022-10-19 21:11

from django.db import migrations


def change_request_app_name_to_blank(apps, schema_editor):
    Request = apps.get_model("watcher", "Request")
    Request.objects.filter(app_name__isnull=True).update(app_name="")


class Migration(migrations.Migration):

    dependencies = [
        ("watcher", "0006_alter_request_started_at"),
    ]

    operations = [
        migrations.RunPython(
            change_request_app_name_to_blank, migrations.RunPython.noop
        ),
    ]
