# Generated by Django 4.1.1 on 2022-10-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watcher", "0007_auto_20221019_2111"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="app_name",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=200
            ),
        ),
    ]
