repos:
- hooks:
  - id: isort
    name: isort (python)
  - id: isort
    name: isort (cython)
    types:
    - cython
  - id: isort
    name: isort (pyi)
    types:
    - pyi
  repo: https://github.com/pycqa/isort
  rev: 5.8.0
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.20.4
