steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "mono/app.yaml"]
    secretEnv:
      [
        "ALLOWED_HOST",
        "APP_ENV",
        "APP_SECRET",
        "DB_ADDR",
        "DB_NAME",
        "DB_PASS",
        "DB_USER",
        "EMAIL_HOST",
        "EMAIL_HOST_PASSWORD",
        "EMAIL_HOST_USER",
        "GITHUB_SECRET",
        "RECAPTCHA_PRIVATE_KEY",
        "RECAPTCHA_PUBLIC_KEY",
        "SOCIAL_AUTH_GITHUB_KEY",
        "SOCIAL_AUTH_GITHUB_SECRET",
        "STRIPE_ENDPOINT_SECRET",
        "STRIPE_PUBLIC_KEY",
        "STRIPE_SECRET_KEY",
        "STRIPE_TIMEZONE",
      ]
availableSecrets:
  secretManager:
    - versionName: projects/monoproject-308518/secrets/ALLOWED_HOST/versions/1
      env: "ALLOWED_HOST"
    - versionName: projects/monoproject-308518/secrets/APP_ENV/versions/1
      env: "APP_ENV"
    - versionName: projects/monoproject-308518/secrets/APP_SECRET/versions/1
      env: "APP_SECRET"
    - versionName: projects/monoproject-308518/secrets/DB_ADDR/versions/1
      env: "DB_ADDR"
    - versionName: projects/monoproject-308518/secrets/DB_NAME/versions/1
      env: "DB_NAME"
    - versionName: projects/monoproject-308518/secrets/DB_PASS/versions/1
      env: "DB_PASS"
    - versionName: projects/monoproject-308518/secrets/DB_USER/versions/1
      env: "DB_USER"
    - versionName: projects/monoproject-308518/secrets/EMAIL_HOST/versions/1
      env: "EMAIL_HOST"
    - versionName: projects/monoproject-308518/secrets/EMAIL_HOST_PASSWORD/versions/1
      env: "EMAIL_HOST_PASSWORD"
    - versionName: projects/monoproject-308518/secrets/EMAIL_HOST_USER/versions/1
      env: "EMAIL_HOST_USER"
    - versionName: projects/monoproject-308518/secrets/GITHUB_SECRET/versions/1
      env: "GITHUB_SECRET"
    - versionName: projects/monoproject-308518/secrets/RECAPTCHA_PRIVATE_KEY/versions/1
      env: "RECAPTCHA_PRIVATE_KEY"
    - versionName: projects/monoproject-308518/secrets/RECAPTCHA_PUBLIC_KEY/versions/1
      env: "RECAPTCHA_PUBLIC_KEY"
    - versionName: projects/monoproject-308518/secrets/SOCIAL_AUTH_GITHUB_KEY/versions/1
      env: "SOCIAL_AUTH_GITHUB_KEY"
    - versionName: projects/monoproject-308518/secrets/SOCIAL_AUTH_GITHUB_SECRET/versions/1
      env: "SOCIAL_AUTH_GITHUB_SECRET"
    - versionName: projects/monoproject-308518/secrets/STRIPE_ENDPOINT_SECRET/versions/1
      env: "STRIPE_ENDPOINT_SECRET"
    - versionName: projects/monoproject-308518/secrets/STRIPE_PUBLIC_KEY/versions/1
      env: "STRIPE_PUBLIC_KEY"
    - versionName: projects/monoproject-308518/secrets/STRIPE_SECRET_KEY/versions/1
      env: "STRIPE_SECRET_KEY"
    - versionName: projects/monoproject-308518/secrets/STRIPE_TIMEZONE/versions/1
      env: "STRIPE_TIMEZONE"
timeout: "1600s"
