steps:
  - id: "deploy app"
    name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "mono/app.yaml"]
  - id: "apply migrations"
    name: "gcr.io/google-appengine/exec-wrapper"
    args: [
        "-i",
        "gcr.io/monoproject-308518/default",
        "-s",
        "monoproject-308518:southamerica-east1:monoprojectdb",
        # "-e",
        # "SETTINGS_NAME=${_SECRET_SETTINGS_NAME}",
        "--",
        "python",
        "mono/manage.py",
        "migrate",
      ]
timeout: "1600s"
