[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "6.14.1"
tag_format = "$version"
version_files = [
    "mono/__mono/settings.py",
    "pyproject.toml:version",
    "VERSION",
]
style = [
    ["qmark", "fg:#ff9d00 bold"],
    ["question", "bold"],
    ["answer", "fg:#ff9d00 bold"],
    ["pointer", "fg:#ff9d00 bold"],
    ["highlighted", "fg:#ff9d00 bold"],
    ["selected", "fg:#cc5454"],
    ["separator", "fg:#cc5454"],
    ["instruction", ""],
    ["text", ""],
    ["disabled", "fg:#858585 italic"]
]

[tool.isort]
src_paths = "isort,test"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 80
combine_as_imports = true

[tool.black]
line-length=80