curl \
  -X POST
  -H "Authorization: Basic uiKmn0%LOT9fIu6uld6apeGnvT5oAo" \
  -H "Content-Type: application/json" \
  -d '{
        "nome":"Rodrigo Eiti Kimura",
        "email":"teste@teste.com"
      }' \
  http://localhost:4245/hs
###
curl \
  -X GET
  http://localhost:4245/hc