"""Default icons to create"""
DEFAULT_ICONS = [
    "address book",
    "address book outline",
    "address card",
    "address card outline",
    "archive",
    "balance scale",
    "balance scale left",
    "balance scale right",
    "birthday cake",
    "book",
    "briefcase",
    "building",
    "building outline",
    "bullhorn",
    "bullseye",
    "business time",
    "calculator",
    "calendar",
    "calendar alternate",
    "calendar alternate outline",
    "calendar outline",
    "certificate",
    "chart area",
    "chart bar",
    "chart bar outline",
    "chart line",
    "chart pie",
    "city",
    "clipboard",
    "clipboard outline",
    "coffee",
    "columns",
    "compass",
    "compass outline",
    "copy",
    "copy outline",
    "copyright",
    "copyright outline",
    "cut",
    "edit",
    "edit outline",
    "envelope",
    "envelope open",
    "envelope open outline",
    "envelope outline",
    "envelope square",
    "eraser",
    "fax",
    "file",
    "file alternate",
    "file alternate outline",
    "file outline",
    "folder",
    "folder minus",
    "folder open",
    "folder open outline",
    "folder outline",
    "folder plus",
    "glasses",
    "globe",
    "highlighter",
    "industry",
    "landmark",
    "laptop house",
    "marker",
    "paperclip",
    "paste",
    "pen",
    "pen alternate",
    "pen fancy",
    "pen nib",
    "pen square",
    "pencil alternate",
    "percent",
    "phone",
    "phone alternate",
    "phone slash",
    "phone square",
    "phone square alternate",
    "phone volume",
    "print",
    "project diagram",
    "registered",
    "registered outline",
    "save",
    "save outline",
    "sitemap",
    "socks",
    "sticky note",
    "sticky note outline",
    "stream",
    "table",
    "tag",
    "tags",
    "tasks",
    "thumbtack",
    "trademark",
    "wallet",
    "archive",
    "barcode",
    "bath",
    "bug",
    "code",
    "code branch",
    "coffee",
    "file",
    "file alternate",
    "file alternate outline",
    "file code",
    "file code outline",
    "file outline",
    "filter",
    "fire extinguisher",
    "folder",
    "folder open",
    "folder open outline",
    "folder outline",
    "keyboard",
    "keyboard outline",
    "laptop code",
    "microchip",
    "project diagram",
    "qrcode",
    "shield alternate",
    "sitemap",
    "stream",
    "terminal",
    "user secret",
    "window close",
    "window close outline",
    "window maximize",
    "window maximize outline",
    "window minimize",
    "window minimize outline",
    "window restore",
    "window restore outline",
    "address book",
    "address book outline",
    "address card",
    "address card outline",
    "american sign language interpreting",
    "assistive listening systems",
    "at",
    "bell",
    "bell outline",
    "bell slash",
    "bell slash outline",
    "bluetooth",
    "bluetooth b",
    "broadcast tower",
    "bullhorn",
    "chalkboard",
    "comment",
    "comment alternate",
    "comment alternate outline",
    "comment outline",
    "comments",
    "comments outline",
    "envelope",
    "envelope open",
    "envelope open outline",
    "envelope outline",
    "envelope square",
    "fax",
    "inbox",
    "language",
    "microphone",
    "microphone alternate",
    "microphone alternate slash",
    "microphone slash",
    "mobile",
    "mobile alternate",
    "paper plane",
    "paper plane outline",
    "phone",
    "phone alternate",
    "phone slash",
    "phone square",
    "phone square alternate",
    "phone volume",
    "rss",
    "rss square",
    "tty",
    "voicemail",
    "wifi",
    "database",
    "desktop",
    "download",
    "ethernet",
    "hdd",
    "hdd outline",
    "headphones",
    "keyboard",
    "keyboard outline",
    "laptop",
    "laptop house",
    "memory",
    "microchip",
    "mobile",
    "mobile alternate",
    "mouse",
    "plug",
    "power off",
    "print",
    "satellite",
    "satellite dish",
    "save",
    "save outline",
    "sd card",
    "server",
    "sim card",
    "stream",
    "tablet",
    "tablet alternate",
    "tv",
    "upload",
    "brush",
    "drafting compass",
    "dumpster",
    "hammer",
    "hard hat",
    "paint roller",
    "pencil alternate",
    "pencil ruler",
    "ruler",
    "ruler combined",
    "ruler horizontal",
    "ruler vertical",
    "screwdriver",
    "toolbox",
    "tools",
    "truck pickup",
    "wrench",
    "bell",
    "bell outline",
    "bell slash",
    "bell slash outline",
    "calendar",
    "calendar alternate",
    "calendar alternate outline",
    "calendar check",
    "calendar check outline",
    "calendar minus",
    "calendar minus outline",
    "calendar outline",
    "calendar plus",
    "calendar plus outline",
    "calendar times",
    "calendar times outline",
    "clock",
    "clock outline",
    "hourglass",
    "hourglass end",
    "hourglass half",
    "hourglass outline",
    "hourglass start",
    "stopwatch",
    "adjust",
    "bezier curve",
    "brush",
    "clone",
    "clone outline",
    "copy",
    "copy outline",
    "crop",
    "crop alternate",
    "crosshairs",
    "cut",
    "drafting compass",
    "draw polygon",
    "edit",
    "edit outline",
    "eraser",
    "eye",
    "eye dropper",
    "eye outline",
    "eye slash",
    "eye slash outline",
    "fill",
    "fill drip",
    "highlighter",
    "icons",
    "layer group",
    "magic",
    "marker",
    "object group",
    "object group outline",
    "object ungroup",
    "object ungroup outline",
    "paint brush",
    "paint roller",
    "palette",
    "paste",
    "pen",
    "pen alternate",
    "pen fancy",
    "pen nib",
    "pencil alternate",
    "pencil ruler",
    "ruler combined",
    "ruler horizontal",
    "ruler vertical",
    "save",
    "save outline",
    "splotch",
    "spray can",
    "stamp",
    "swatchbook",
    "tint",
    "tint slash",
    "vector square",
    "atom",
    "award",
    "bell",
    "bell outline",
    "bell slash",
    "bell slash outline",
    "book open",
    "book reader",
    "chalkboard",
    "chalkboard teacher",
    "fruit-apple",
    "graduation cap",
    "laptop code",
    "microscope",
    "music",
    "school",
    "shapes",
    "theater masks",
    "user graduate",
]
