# Generated by Django 4.2.5 on 2023-09-20 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feeling",
                    models.IntegerField(
                        choices=[
                            (1, "angry"),
                            (2, "cry"),
                            (3, "slight_frown"),
                            (4, "expressionless"),
                            (5, "slight_smile"),
                            (6, "grinning"),
                            (7, "heart_eyes"),
                        ],
                        verbose_name="feeling",
                    ),
                ),
                (
                    "message",
                    models.TextField(max_length=1000, verbose_name="message"),
                ),
                (
                    "public",
                    models.BooleanField(default=False, verbose_name="public"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
    ]
