# Generated by Django 3.2.11 on 2022-01-25 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('feedback', '0001_initial'), ('feedback', '0002_alter_feedback_feeling'), ('feedback', '0003_auto_20210414_1333')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.IntegerField(choices=[(1, 'angry'), (2, 'cry'), (3, 'slight_frown'), (4, 'expressionless'), (5, 'slight_smile'), (6, 'grinning'), (7, 'heart_eyes')], verbose_name='feeling')),
                ('message', models.TextField(max_length=1000, verbose_name='message')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('public', models.BooleanField(default=False, verbose_name='public')),
            ],
        ),
    ]
