# Generated by Django 3.2 on 2021-04-14 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.IntegerField(choices=[(1, 'angry'), (2, 'cry'), (3, 'anguished'), (4, 'confused'), (5, 'disappointed'), (6, 'expressionless'), (7, 'frowning2'), (8, 'frowning'), (9, 'slight_frown'), (10, 'slight_smile'), (11, 'grinning'), (12, 'heart_eyes')], max_length=3, verbose_name='feeling')),
                ('message', models.TextField(max_length=1000, verbose_name='message')),
                ('private', models.BooleanField(default=False, verbose_name='private')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
