# Generated by Django 3.2 on 2021-04-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feeling',
            field=models.IntegerField(choices=[(1, 'angry'), (2, 'cry'), (3, 'anguished'), (4, 'confused'), (5, 'disappointed'), (6, 'expressionless'), (7, 'frowning2'), (8, 'frowning'), (9, 'slight_frown'), (10, 'slight_smile'), (11, 'grinning'), (12, 'heart_eyes')], verbose_name='feeling'),
        ),
    ]
