# Generated by Django 3.2 on 2021-04-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_feeling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='private',
        ),
        migrations.AddField(
            model_name='feedback',
            name='public',
            field=models.BooleanField(default=False, verbose_name='public'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feeling',
            field=models.IntegerField(choices=[(1, 'angry'), (2, 'cry'), (3, 'slight_frown'), (4, 'expressionless'), (5, 'slight_smile'), (6, 'grinning'), (7, 'heart_eyes')], verbose_name='feeling'),
        ),
    ]
