DEFAULT_ICONS = [
    "heartbeat",
    "beer",
    "coffee",
    "bath",
    "bed",
    "bicycle",
    "book",
    "car",
    "gamepad",
    "graduation cap",
    "home",
    "money bill alternate outline",
    "plug",
    "utensils",
    "wrench",
    "bell",
    "exclamation",
    "cart",
    "university",
    "chart bar",
    "birthday cake",
    "plane",
    "globe",
    "tasks",
    "tag",
    "tags",
    "gift",
    "mobile alternate",
    "tv",
    "credit card",
    "suitcase",
    "shopping basket",
]