# Generated by Django 3.2.11 on 2022-01-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("homepage", "0001_initial"),
        ("homepage", "0002_alter_module_id"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
