# Generated by Django 3.2 on 2021-04-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("background_task", "0002_auto_20170927_1109"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedtask",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
