# Generated by Django 4.1.4 on 2022-12-15 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("typer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="keypress",
            old_name="miliseconds",
            new_name="milliseconds",
        ),
    ]
