# Generated by Django 4.1.4 on 2022-12-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("typer", "0003_record_accuracy_record_chars_per_minute"),
    ]

    operations = [
        migrations.AddField(
            model_name="keypress",
            name="correct",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="keypress",
            name="character",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="keypress",
            name="milliseconds",
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
