# Generated by Django 4.1.4 on 2022-12-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("typer", "0004_keypress_correct_alter_keypress_character_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keypress",
            name="correct",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
