# Generated by Django 3.2 on 2021-06-11 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_todo_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
