# Generated by Django 3.2.7 on 2021-09-15 20:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=1024, null=True)),
                ('event', models.CharField(max_length=1024, null=True)),
                ('event_data', models.CharField(max_length=1024, null=True)),
                ('openpixel_js_version', models.CharField(max_length=1024, null=True)),
                ('document_location', models.CharField(max_length=1024, null=True)),
                ('referrer_location', models.CharField(max_length=1024, null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('encoding', models.CharField(max_length=1024, null=True)),
                ('screen_resolution', models.CharField(max_length=50, null=True)),
                ('viewport', models.CharField(max_length=50, null=True)),
                ('document_title', models.CharField(max_length=1024, null=True)),
                ('browser_name', models.CharField(max_length=1024, null=True)),
                ('mobile_device', models.BooleanField(null=True)),
                ('user_agent', models.CharField(max_length=1024, null=True)),
                ('timezone_offset', models.IntegerField(null=True)),
                ('utm_source', models.CharField(max_length=1024, null=True)),
                ('utm_medium', models.CharField(max_length=1024, null=True)),
                ('utm_term', models.CharField(max_length=1024, null=True)),
                ('utm_content', models.CharField(max_length=1024, null=True)),
                ('utm_campaign', models.CharField(max_length=1024, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixel.site')),
            ],
        ),
    ]
