# Generated by Django 4.2.5 on 2023-09-20 19:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        help_text="Host of the URL. Port or userinfo should be ommited. https://en.wikipedia.org/wiki/URL",
                        max_length=1024,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=1024, null=True)),
                ("event", models.CharField(max_length=1024, null=True)),
                ("event_data", models.CharField(max_length=1024, null=True)),
                (
                    "openpixel_js_version",
                    models.CharField(max_length=1024, null=True),
                ),
                (
                    "document_location",
                    models.CharField(max_length=1024, null=True),
                ),
                (
                    "referrer_location",
                    models.CharField(max_length=1024, null=True),
                ),
                ("timestamp", models.DateTimeField(null=True)),
                ("encoding", models.CharField(max_length=1024, null=True)),
                (
                    "screen_resolution",
                    models.CharField(max_length=50, null=True),
                ),
                ("viewport", models.CharField(max_length=50, null=True)),
                (
                    "document_title",
                    models.CharField(max_length=1024, null=True),
                ),
                ("browser_name", models.CharField(max_length=1024, null=True)),
                ("mobile_device", models.BooleanField(null=True)),
                ("user_agent", models.CharField(max_length=1024, null=True)),
                ("timezone_offset", models.IntegerField(null=True)),
                ("utm_source", models.CharField(max_length=1024, null=True)),
                ("utm_medium", models.CharField(max_length=1024, null=True)),
                ("utm_term", models.CharField(max_length=1024, null=True)),
                ("utm_content", models.CharField(max_length=1024, null=True)),
                ("utm_campaign", models.CharField(max_length=1024, null=True)),
                ("pageload_timestamp", models.DateTimeField(null=True)),
                ("pageclose_timestamp", models.DateTimeField(null=True)),
                ("duration", models.DurationField(null=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pixel.site",
                    ),
                ),
            ],
        ),
    ]
