# Generated by Django 3.2.7 on 2021-09-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='host',
            field=models.CharField(help_text='Host of the URL. Port or userinfo should be ommited. https://en.wikipedia.org/wiki/URL', max_length=1024, null=True),
        ),
    ]
