# Generated by Django 3.2.13 on 2022-04-21 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0002_auto_20220125_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['created_at']},
        ),
    ]
