# Generated by Django 3.2.7 on 2021-09-16 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0002_site_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='ping',
            name='pageclose_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ping',
            name='pageload_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
