# Generated by Django 3.2.7 on 2021-09-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0003_auto_20210916_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ping',
            name='pageload_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
