# Generated by Django 3.2.7 on 2021-09-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0006_site_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
