# Generated by Django 3.2.11 on 2022-01-25 16:40

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("accounts", "0001_initial"),
        ("accounts", "0002_auto_20210401_1751"),
        ("accounts", "0003_userprofile_verified_at"),
        ("accounts", "0004_alter_userprofile_id"),
        ("accounts", "0005_alter_userprofile_user"),
        ("accounts", "0006_notification"),
        ("accounts", "0007_alter_notification_options"),
        ("accounts", "0008_feature_plan_subscription"),
        ("accounts", "0009_alter_plan_type"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=accounts.models.user_directory_path,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("message", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("icon", models.CharField(default="bell", max_length=50)),
                (
                    "read_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True, default=None, max_length=1000, null=True
                    ),
                ),
                (
                    "to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        help_text="Stores the stripe unique identifiers",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name used on the template",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description text used on the template",
                        max_length=500,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Icon rendered in the template", max_length=50
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FR", "Free"),
                            ("LT", "Lifetime"),
                            ("DF", "Default"),
                            ("RC", "Recommended"),
                        ],
                        help_text="Used to customize the template based on this field.For instance, the basic plan will be muted and the recommended one is highlighted.",
                        max_length=2,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="Used to sort plans on the template.",
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "plan",
                "verbose_name_plural": "plans",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cancel_at", models.DateTimeField(blank=True, null=True)),
                ("event_id", models.CharField(max_length=100)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.plan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Icon rendered in the template", max_length=50
                    ),
                ),
                ("short_description", models.CharField(max_length=30)),
                ("full_description", models.TextField(max_length=200)),
                (
                    "internal_description",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="This is used by staff and is not displayed to user in the template.",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "display",
                    models.BooleanField(
                        default=True,
                        help_text="Controls wether feature is shown on the template",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "feature",
                "verbose_name_plural": "features",
            },
        ),
    ]
