# Generated by Django 3.1.5 on 2021-01-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('', 'Selecione uma opção'), ('m', 'Masculino'), ('f', 'Feminino'), ('n', 'Não informar')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
