# Generated by Django 3.1.7 on 2021-04-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210401_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
