# Generated by Django 3.1.5 on 2021-01-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210123_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(height_field=20, null=True, upload_to='', width_field=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('', 'Gender'), ('m', 'Male'), ('f', 'Female'), ('n', 'I prefer not to say')], max_length=1),
        ),
    ]
