# Generated by Django 3.2.13 on 2022-07-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_user_token',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
