# Generated by Django 3.2.13 on 2022-08-10 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_firebasecloudmessagingtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firebasecloudmessagingtoken',
            options={'verbose_name': 'firebase cloud messaging token', 'verbose_name_plural': 'firebase cloud messaging tokens'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.AlterField(
            model_name='firebasecloudmessagingtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
