# Generated by Django 3.2.13 on 2022-08-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220810_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebasecloudmessagingtoken',
            name='token',
            field=models.TextField(max_length=200, unique=True),
        ),
    ]
