# Generated by Django 3.2.7 on 2021-10-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['created_at'], 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
    ]
