# Generated by Django 3.2.11 on 2022-01-20 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_alter_notification_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(help_text='Stores the stripe unique identifiers', max_length=100)),
                ('name', models.CharField(help_text='Display name used on the template', max_length=100)),
                ('description', models.TextField(help_text='Description text used on the template', max_length=500)),
                ('icon', models.CharField(help_text='Icon rendered in the template', max_length=50)),
                ('type', models.CharField(choices=[('FR', 'Free'), ('LT', 'Lifetime'), ('DF', 'Default'), ('RC', 'Recommended')], help_text='Used to customize the template based on this field. For instance, the basic plan will be muted and the recommended one is highlighted.', max_length=2)),
                ('order', models.IntegerField(help_text='Used to sort plans on the template.', unique=True)),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancel_at', models.DateTimeField(blank=True, null=True)),
                ('event_id', models.CharField(max_length=100)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Icon rendered in the template', max_length=50)),
                ('short_description', models.CharField(max_length=30)),
                ('full_description', models.TextField(max_length=200)),
                ('internal_description', models.TextField(blank=True, default=None, help_text='This is used by staff and is not displayed to user in the template.', max_length=1000, null=True)),
                ('display', models.BooleanField(default=True, help_text='Controls wether feature is shown on the template')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.plan')),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
            },
        ),
    ]
