# Generated by Django 3.2.11 on 2022-01-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_feature_plan_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('FR', 'Free'), ('LT', 'Lifetime'), ('DF', 'Default'), ('RC', 'Recommended')], help_text='Used to customize the template based on this field.For instance, the basic plan will be muted and the recommended one is highlighted.', max_length=2),
        ),
    ]
