# Generated by Django 3.2.13 on 2022-04-29 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="checklist",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="checklists.checklist",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
