# Generated by Django 3.2.13 on 2022-05-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0002_auto_20220429_1654"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="note",
            field=models.TextField(default="", max_length=2000),
        ),
    ]
