# Generated by Django 3.2.13 on 2022-05-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0004_auto_20220512_1840"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="reminder",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
