# Generated by Django 3.2.13 on 2022-05-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0008_task_recurrence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
