# Generated by Django 3.2.13 on 2022-07-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0010_task_next_task_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="note",
            field=models.TextField(blank=True, default="", max_length=2000),
        ),
    ]
