classDiagram
  class AdminTests {
    fixtures : list
  }
  class ChangelogView {
    get(request)
    test_func()
  }
  class CommitsByDateSerializer {
    date : DateField
    create(validated_data)
    update(instance, validated_data)
  }
  class CommitsByDateView {
    fixtures : list
    superuser
    user
    setUp() -> None
    test_get()
    test_get_bad_request()
    test_get_forbidden()
  }
  class CommitsByDateView {
    get(request)
    test_func()
  }
  class CommitsFormattedForHeatmapView {
    get(request)
    test_func()
  }
  class CoverageReport {
    coverage_percentage
    coverage_version : CharField
    created_at : DateTimeField
    result_count
    process_file(report_file)
  }
  class CoverageReportAdmin {
    list_display : tuple
    list_filter : list
  }
  class CoverageReportViewSet {
    permission_classes : tuple
    serializer_class
    create(request)
    list(request)
  }
  class CoverageResult {
    coverage_percentage
    covered_lines : PositiveIntegerField
    excluded_lines : PositiveIntegerField
    file : CharField
    missing_lines : PositiveIntegerField
    num_statements : PositiveIntegerField
    report : ForeignKey
  }
  class CoverageResultAdmin {
    list_display : list
    list_filter : list
  }
  class Deploy {
    template_name : str
    get_context_data()
    post(request)
    test_func()
  }
  class DeployView {
    fixtures : list
    pull_request
    superuser
    user
    setUp() -> None
    test_get()
    test_invalid_user()
    test_post()
  }
  class GithubWebhookView {
    valid_payload : dict
    setUp() -> None
    test_invalid_event()
    test_invalid_signature()
    test_invalid_signature_algorithm()
    test_ping()
    test_valid_signature()
  }
  class HealthCheckView {
    test_get()
  }
  class HealthcheckConfig {
    name : str
  }
  class HealthcheckHomePage {
    template_name : str
    test_func()
  }
  class HomePageView {
    fixtures : list
    superuser
    user
    setUp() -> None
    test_get()
    test_get_forbidden()
  }
  class Meta {
    get_latest_by : str
    verbose_name : str
    verbose_name_plural : str
  }
  class Meta {
    verbose_name : __proxy__
    verbose_name_plural : __proxy__
  }
  class Meta {
    verbose_name : __proxy__
    verbose_name_plural : __proxy__
  }
  class Meta {
    verbose_name : __proxy__
    verbose_name_plural : __proxy__
  }
  class Meta {
    verbose_name : __proxy__
    verbose_name_plural : __proxy__
  }
  class Meta {
    verbose_name : __proxy__
    verbose_name_plural : __proxy__
  }
  class Meta {
    verbose_name : __proxy__
    verbose_name_plural : __proxy__
  }
  class Migration {
    dependencies : list
    initial : bool
    operations : list
    replaces : list
  }
  class Migration {
    dependencies : list
    operations : list
  }
  class Migration {
    dependencies : list
    operations : list
  }
  class Migration {
    dependencies : list
    operations : list
  }
  class Migration {
    dependencies : list
    operations : list
  }
  class Migration {
    dependencies : list
    operations : list
  }
  class Migration {
    dependencies : list
    operations : list
  }
  class Migration {
    dependencies : list
    operations : list
  }
  class MigrationsTests {
    test_no_migrations_to_make()
  }
  class ModelTests {
    pull_request
    setUp() -> None
    test_merged()
    test_pull()
  }
  class Outcome {
    name
  }
  class PullRequest {
    additions : IntegerField
    author : CharField
    build_number
    changed_files : IntegerField
    commits : IntegerField
    deletions : IntegerField
    deployed
    deployed_at : DateTimeField
    last_commit_sha : CharField
    link
    merged
    merged_at : DateTimeField
    migrations : IntegerField
    number : IntegerField
    pulled
    pulled_at : DateTimeField
    pulled_at : datetime
    received_at : DateTimeField
    pull()
  }
  class PullRequestAdmin {
    list_display : list
    list_filter : list
  }
  class PullRequestModelTests {
    pull_request
    setUp()
    test_pull_request_creation()
  }
  class PylintReport {
    created_at : DateTimeField
    result_count
    process_file(report_file)
  }
  class PylintReportAdmin {
    list_display : tuple
    list_filter : tuple
  }
  class PylintReportViewSet {
    permission_classes : tuple
    serializer_class
    create(request)
    list(request)
  }
  class PylintResult {
    column : PositiveIntegerField
    end_column : PositiveIntegerField
    end_line : PositiveIntegerField
    line : PositiveIntegerField
    message : CharField
    message_id : CharField
    module : CharField
    obj : CharField
    path : CharField
    report : ForeignKey
    symbol : CharField
    type : CharField
  }
  class PylintResultAdmin {
    list_display : tuple
    list_filter : tuple
    search_fields : tuple
  }
  class PytestReport {
    created_at : DateTimeField
    duration
    pytest_version : CharField
    result_count
    process_file(report_file)
  }
  class PytestReportAdmin {
    list_display : list
    list_filter : list
  }
  class PytestReportViewSet {
    permission_classes : tuple
    serializer_class
    create(request)
    list(request)
  }
  class PytestResult {
    duration : DurationField
    node_id : CharField
    outcome : CharField
    report : ForeignKey
  }
  class PytestResultAdmin {
    list_display : list
    list_filter : list
    search_fields : tuple
  }
  class ReportSerializer {
    report_file : FileField
  }
  class TaskTests {
    pull_request
    setUp() -> None
    test_task()
  }
  PullRequest --* ModelTests : pull_request
  PullRequest --* TaskTests : pull_request
  ReportSerializer --* CoverageReportViewSet : serializer_class
  ReportSerializer --* PylintReportViewSet : serializer_class
  ReportSerializer --* PytestReportViewSet : serializer_class
