classDiagram
  class Feedback {
    FEELING_CHOICES : list
    feeling : IntegerField
    message : TextField
    public : BooleanField
    user : ForeignKey
  }
  class FeedbackAdmin {
    list_display : list
    list_filter : list
  }
  class FeedbackConfig {
    default_auto_field : str
    name : str
  }
  class FeedbackCreateView {
    form_class
    model
    success_message
    success_url : __proxy__
    get_context_data()
  }
  class FeedbackForm {
    error_css_class : str
    request
    save()
  }
  class FeedbackViewTests {
    factory : RequestFactory
    feedback
    fixtures : list
    user
    setUp()
    test_feedback_creation()
    test_feedback_view()
  }
  class Meta {
    error_messages : dict
    fields : list
    model
    widgets : dict
  }
  class Migration {
    dependencies : list
    initial : bool
    operations : list
    replaces : list
  }
  FeedbackForm --* FeedbackCreateView : form_class
  Feedback --* Meta : model
  Feedback --* FeedbackCreateView : model
