classDiagram
  class AdminTests {
    admin
    fixtures : list
    request : WSGIRequest
    user
    setUp()
    test_flush_pings()
    test_undo_deletion()
  }
  class DashboardAggregatedByDateApiView {
    process_data()
  }
  class DashboardAggregatedByDocLocApiView {
    process_data()
  }
  class DashboardBaseApiView {
    pings : NoneType
    site : NoneType
    get(request, pk)
    process_data()
  }
  class DashboardGeneralInfoApiView {
    process_data()
  }
  class DashboardView {
    model
    template_name : str
    test_func()
  }
  class FormTests {
    fixtures : list
    test_site_form()
  }
  class Meta {
    fields : list
    model
  }
  class Migration {
    dependencies : list
    initial : bool
    operations : list
    replaces : list
  }
  class Migration {
    dependencies : list
    operations : list
  }
  class Ping {
    browser_name : CharField
    document_location : CharField
    document_title : CharField
    duration : DurationField
    encoding : CharField
    event : CharField
    event_data : CharField
    mobile_device : BooleanField
    openpixel_js_version : CharField
    pageclose_timestamp : DateTimeField
    pageload_timestamp : DateTimeField
    referrer_location : CharField
    screen_resolution : CharField
    site : ForeignKey
    timestamp : DateTimeField
    timezone_offset : IntegerField
    user_agent : CharField
    user_id : CharField
    utm_campaign : CharField
    utm_content : CharField
    utm_medium : CharField
    utm_source : CharField
    utm_term : CharField
    viewport : CharField
  }
  class PingAdmin {
    list_display : list
    list_filter : list
  }
  class PixelConfig {
    default_auto_field : str
    name : str
  }
  class RootView {
    permanent : bool
    query_string : bool
    get_redirect_url()
  }
  class Site {
    created_at : DateTimeField
    created_by : ForeignKey
    deleted_at : DateTimeField
    deleted_at : datetime
    host : CharField
    id : UUIDField
    snippet
    flush_pings()
    get_avg_duration(pings)
    get_bounce_rate(pings)
    get_browsers(pings)
    get_document_locations(pings)
    get_online_users()
    get_pings(initial_datetime, final_datetime)
    get_referrer_locations(pings)
    get_views(pings)
    get_visitors(pings)
    soft_delete()
  }
  class SiteAdmin {
    actions : list
    list_display : list
    list_filter : list
    flush_pings(request, queryset)
    undo_deletion(request, queryset)
  }
  class SiteCreateView {
    form_class
    model
    success_url : __proxy__
  }
  class SiteDetailApiView {
    delete(request, pk)
  }
  class SiteForm {
    error_css_class : str
    request
    save() -> Site
  }
  class SitesView {
    model
    get_queryset() -> QuerySet[Site]
  }
  class ViewTests {
    test_root_non_authenticated_user()
  }
  DashboardAggregatedByDateApiView --|> DashboardBaseApiView
  DashboardAggregatedByDocLocApiView --|> DashboardBaseApiView
  DashboardGeneralInfoApiView --|> DashboardBaseApiView
  SiteAdmin --* AdminTests : admin
  SiteForm --* SiteCreateView : form_class
  Site --* Meta : model
  Site --* DashboardView : model
  Site --* SiteCreateView : model
  Site --* SitesView : model
