classDiagram
  class HomepageConfig {
    name : str
  }
  class HomepageView {
    template_name : str
  }
  class Login {
    template_name : str
  }
  class Migration {
    dependencies : list
    initial : bool
    operations : list
    replaces : list
  }
  class ModelTests {
    test_module()
  }
  class Module {
    active : BooleanField
    name : CharField
  }
