classDiagram
  class CompoundWord {
  }
  class CompoundWordPair {
    first
    second
    word_pairs
    get_portmanteaus(same_direction: bool) -> List[Portmanteau]
  }
  class Meta {
    fields : list
    model
    widgets : dict
  }
  class Meta {
    ordering : list
  }
  class Migration {
    dependencies : list
    initial : bool
    operations : list
    replaces : list
  }
  class ModelTests {
    test_portmanteaus()
    test_ship_str()
  }
  class Morpheme {
  }
  class Portmanteau {
    first_flag_onwards : BooleanField
    first_index : SmallIntegerField
    first_parent : CharField
    first_partial
    first_summary
    is_inverted : BooleanField
    second_flag_onwards : BooleanField
    second_index : SmallIntegerField
    second_parent : CharField
    second_partial
    second_summary
    ship : ForeignKey
  }
  class Portmanteau {
    first_config : PortmanteauConfig
    first_parent
    first_partial
    first_remainder
    first_summary
    inverted : bool
    second_config : PortmanteauConfig
    second_parent
    second_partial
    second_remainder
    second_summary
  }
  class PortmanteauAdmin {
    list_display : list
    list_filter : list
    search_fields : list
  }
  class PortmanteauConfig {
    index : int
    onwards : bool
    parent
  }
  class Ship {
    created_at : DateTimeField
    id : UUIDField
    name_1 : CharField
    name_2 : CharField
    generate_portmanteaus()
  }
  class ShipAdmin {
    list_display : list
    list_filter : list
    search_fields : list
  }
  class ShipCreateView {
    form_class
    model
    get_form_kwargs()
    get_success_url()
  }
  class ShipDetailView {
    model
  }
  class ShipForm {
    error_css_class : str
  }
  class ShipView {
    template_name : str
    get_context_data()
  }
  class ShipperConfig {
    default_auto_field : str
    name : str
    ready()
  }
  class ViewTests {
    test_create_view_get()
    test_create_view_post()
    test_root()
  }
  class Word {
    morphemes
    text
  }
  class WordPair {
    first
    second
    get_portmanteaus(same_direction: bool) -> List[Portmanteau]
  }
  ShipForm --* ShipCreateView : form_class
  Ship --* Meta : model
  Ship --* ShipCreateView : model
  Ship --* ShipDetailView : model
  CompoundWord --* CompoundWordPair : first
  CompoundWord --* CompoundWordPair : second
  Portmanteau --* Portmanteau : _portmanteau
  Word --* PortmanteauConfig : parent
  Word --* WordPair : first
  Word --* WordPair : second
