classDiagram
  class pixel {
  }
  class admin {
  }
  class apps {
  }
  class forms {
  }
  class migrations {
  }
  class 0001_squashed_0007_site_deleted_at {
  }
  class 0002_auto_20220125_1646 {
  }
  class models {
  }
  class tests {
  }
  class urls {
  }
  class views {
  }
  forms --> models
  tests --> admin
  tests --> forms
  tests --> models
  views --> forms
  views --> models
