classDiagram
  class feedback {
  }
  class admin {
  }
  class apps {
  }
  class forms {
  }
  class migrations {
  }
  class 0001_squashed_0003_auto_20210414_1333 {
  }
  class models {
  }
  class tests {
  }
  class urls {
  }
  class views {
  }
  forms --> models
  tests --> models
  tests --> views
  views --> forms
  views --> models
