classDiagram
  class coder {
  }
  class admin {
  }
  class apps {
  }
  class migrations {
  }
  class 0001_initial {
  }
  class 0002_auto_20220209_2017 {
  }
  class 0003_auto_20220210_1425 {
  }
  class 0004_auto_20220211_1424 {
  }
  class 0005_alter_tag_color {
  }
  class 0006_alter_snippet_tags {
  }
  class 0007_rename_user_configuration_created_by {
  }
  class models {
  }
  class serializers {
  }
  class tests {
  }
  class urls {
  }
  class views {
  }
  class viewsets {
  }
  serializers --> models
  urls --> viewsets
  views --> models
  views --> serializers
  viewsets --> models
  viewsets --> serializers
