classDiagram
  class homepage {
  }
  class admin {
  }
  class apps {
  }
  class migrations {
  }
  class 0001_squashed_0002_alter_module_id {
  }
  class models {
  }
  class tests {
  }
  class urls {
  }
  class views {
  }
  tests --> models
