classDiagram
  class watcher {
  }
  class admin {
  }
  class apps {
  }
  class log_handlers {
  }
  class middlewares {
  }
  class migrations {
  }
  class 0001_squashed_0007_alter_issue_options {
  }
  class 0002_request {
  }
  class 0003_alter_request_route {
  }
  class models {
  }
  class serializers {
  }
  class tests {
  }
  class urls {
  }
  class views {
  }
  log_handlers --> models
  middlewares --> models
  views --> models
  views --> serializers
