classDiagram
  class shipper {
  }
  class admin {
  }
  class apps {
  }
  class forms {
  }
  class migrations {
  }
  class 0001_squashed_0005_alter_ship_options {
  }
  class models {
  }
  class signals {
  }
  class tests {
  }
  class urls {
  }
  class utils {
  }
  class views {
  }
  forms --> models
  models --> utils
  signals --> models
  tests --> models
  views --> forms
  views --> models
