classDiagram
  class notes {
  }
  class admin {
  }
  class apps {
  }
  class forms {
  }
  class migrations {
  }
  class 0001_squashed_0002_alter_tag_created_by {
  }
  class 0002_alter_note_options {
  }
  class models {
  }
  class serializers {
  }
  class tests {
  }
  class urls {
  }
  class views {
  }
  forms --> models
  serializers --> models
  views --> forms
  views --> models
  views --> serializers
