classDiagram
  class blog {
  }
  class admin {
  }
  class apps {
  }
  class forms {
  }
  class migrations {
  }
  class 0001_squashed_0002_auto_20210420_1824 {
  }
  class models {
  }
  class tests {
  }
  class urls {
  }
  class views {
  }
  forms --> models
  tests --> models
  views --> forms
  views --> models
