# Generated by Django 3.2.12 on 2022-02-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum_builder", "0002_auto_20220202_1628"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acomplishment",
            options={"ordering": ("work_experience", "order")},
        ),
    ]
