# Generated by Django 3.2.12 on 2022-03-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum_builder", "0007_curriculum_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curriculum",
            name="style",
            field=models.CharField(
                choices=[
                    ("semantic", "Semantic"),
                    ("typewriter", "Typewriter"),
                ],
                default="semantic",
                max_length=50,
            ),
        ),
    ]
