# Generated by Django 4.1 on 2022-09-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mind_maps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="x",
            field=models.IntegerField(default=1000.0),
        ),
        migrations.AlterField(
            model_name="node",
            name="y",
            field=models.IntegerField(default=1000.0),
        ),
    ]
