# Generated by Django 4.1 on 2022-09-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mind_maps", "0002_alter_node_x_alter_node_y"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="font_size",
            field=models.IntegerField(default=14),
        ),
    ]
