# Generated by Django 4.1 on 2022-09-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mind_maps", "0003_node_font_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="padding",
            field=models.IntegerField(default=10),
        ),
    ]
