# Generated by Django 4.1 on 2022-09-07 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mind_maps", "0004_node_padding"),
    ]

    operations = [
        migrations.AddField(
            model_name="mindmap",
            name="scale",
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name="node",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mind_maps.node",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="x",
            field=models.IntegerField(default=120.0),
        ),
        migrations.AlterField(
            model_name="node",
            name="y",
            field=models.IntegerField(default=120.0),
        ),
    ]
