# Generated by Django 4.1 on 2022-09-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mind_maps",
            "0005_mindmap_scale_alter_node_parent_alter_node_x_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="font_size",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="node",
            name="padding",
            field=models.IntegerField(default=1),
        ),
    ]
