# Generated by Django 4.1 on 2022-09-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mind_maps", "0006_alter_node_font_size_alter_node_padding"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="bold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="node",
            name="italic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="node",
            name="line_through",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="node",
            name="underline",
            field=models.BooleanField(default=False),
        ),
    ]
