# Generated by Django 4.1 on 2022-09-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mind_maps", "0007_node_bold_node_italic_node_line_through_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="font_size",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="node",
            name="padding",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="node",
            name="x",
            field=models.FloatField(default=120.0),
        ),
        migrations.AlterField(
            model_name="node",
            name="y",
            field=models.FloatField(default=120.0),
        ),
    ]
