# Generated by Django 4.1 on 2022-09-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mind_maps", "0009_node_background_color_node_border_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="collapsed",
            field=models.BooleanField(default=False),
        ),
    ]
