# Generated by Django 4.1 on 2022-09-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mind_maps", "0010_node_collapsed"),
    ]

    operations = [
        migrations.AddField(
            model_name="mindmap",
            name="color",
            field=models.CharField(default="#000000", max_length=7),
        ),
    ]
