# Generated by Django 3.2.4 on 2021-07-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='location',
            field=models.CharField(default='', help_text="Note's location in format of a path of folders separated by '/'", max_length=2000),
            preserve_default=False,
        ),
    ]
