# Generated by Django 3.2.12 on 2022-04-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_squashed_0002_alter_tag_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={
                "ordering": ("location", "title"),
                "verbose_name": "note",
                "verbose_name_plural": "notes",
            },
        ),
    ]
