# Generated by Django 3.2.4 on 2021-07-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='location',
            field=models.CharField(blank=True, default='', help_text="Note's location in path-like format (eg.: random/stuff)", max_length=2000),
        ),
    ]
