# Generated by Django 3.2.4 on 2021-07-25 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_alter_note_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='location',
            field=models.CharField(blank=True, default='', help_text="Note's location in path-like format (eg.: random/stuff)", max_length=2000, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(help_text="Note's title.", max_length=200, verbose_name='title'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tag's name.", max_length=100, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(help_text='Identifies who created the tag.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
        ),
    ]
