# Generated by Django 3.2.4 on 2021-07-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='location',
            field=models.CharField(blank=True, default='', help_text="Note's location in format of a path of folders separated by '/'", max_length=2000),
        ),
    ]
