# Generated by Django 3.2.4 on 2021-07-15 11:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0003_alter_note_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('title', 'location', 'created_by')},
        ),
    ]
