# Generated by Django 3.1.7 on 2021-03-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('author', models.CharField(max_length=100)),
                ('commits', models.IntegerField(default=0)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('changed_files', models.IntegerField(default=0)),
                ('merged_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('received_at', models.DateTimeField(auto_now=True)),
                ('pulled_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deployed_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
