# Generated by Django 3.1.7 on 2021-03-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
