# Generated by Django 3.2.13 on 2022-04-16 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0002_pytestreport_pytesttestresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covearge_version', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoverageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(help_text='File name.', max_length=2000)),
                ('covered_lines', models.PositiveIntegerField()),
                ('missing_lines', models.PositiveIntegerField()),
                ('excluded_lines', models.PositiveIntegerField()),
                ('num_statements', models.PositiveIntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='healthcheck.coveragereport')),
            ],
        ),
    ]
