# Generated by Django 3.1.7 on 2021-03-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0002_auto_20210318_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='author',
            field=models.CharField(help_text='Login username that triggered the pull request.', max_length=100),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='number',
            field=models.IntegerField(help_text='GitHub unique identifier.', unique=True),
        ),
    ]
