# Generated by Django 3.1.7 on 2021-03-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0003_auto_20210318_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='deployed_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Updated when deploy method runs.', null=True),
        ),
    ]
