# Generated by Django 3.2.13 on 2022-04-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("healthcheck", "0003_coveragereport_coverageresult"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coveragereport",
            old_name="covearge_version",
            new_name="coverage_version",
        ),
    ]
