# Generated by Django 3.2.13 on 2022-04-17 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0004_rename_covearge_version_coveragereport_coverage_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='PylintReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PylintResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='File name.', max_length=50)),
                ('module', models.CharField(help_text='Module name.', max_length=1000)),
                ('obj', models.CharField(help_text='Object within the module (if any).', max_length=1000)),
                ('line', models.PositiveIntegerField(help_text='Line number.', null=True)),
                ('column', models.PositiveIntegerField(help_text='Column number.', null=True)),
                ('endLine', models.PositiveIntegerField(help_text='Line number of the end of the node.', null=True)),
                ('endColumn', models.PositiveIntegerField(help_text='Column number of the end of the node.', null=True)),
                ('path', models.CharField(help_text='Relative path to the file.', max_length=1000)),
                ('symbol', models.CharField(help_text='Symbolic name of the message.', max_length=50)),
                ('message', models.CharField(help_text='Text of the message.', max_length=100)),
                ('message_id', models.CharField(help_text='Message code.', max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='healthcheck.pylintreport')),
            ],
        ),
    ]
