# Generated by Django 3.1.7 on 2021-03-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0004_auto_20210318_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='pulled_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Updated when pull method runs.', null=True),
        ),
    ]
