# Generated by Django 3.2.13 on 2022-04-17 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0005_pylintreport_pylintresult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PytestTestResult',
            new_name='PytestResult',
        ),
        migrations.AlterModelOptions(
            name='coveragereport',
            options={'verbose_name': 'Coverage Report', 'verbose_name_plural': 'Coverage Reports'},
        ),
        migrations.AlterModelOptions(
            name='coverageresult',
            options={'verbose_name': 'Coverage Result', 'verbose_name_plural': 'Coverage Results'},
        ),
        migrations.AlterModelOptions(
            name='pylintreport',
            options={'verbose_name': 'Pylint Report', 'verbose_name_plural': 'Pylint Reports'},
        ),
        migrations.AlterModelOptions(
            name='pylintresult',
            options={'verbose_name': 'Pylint Result', 'verbose_name_plural': 'Pylint Results'},
        ),
        migrations.AlterModelOptions(
            name='pytestreport',
            options={'verbose_name': 'Pytest Report', 'verbose_name_plural': 'Pytest Reports'},
        ),
    ]
