# Generated by Django 3.1.7 on 2021-03-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0005_auto_20210318_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='deployed_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Set when deploy method runs.', null=True),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='pulled_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Set when pull method runs.', null=True),
        ),
    ]
