# Generated by Django 3.1.7 on 2021-03-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0006_auto_20210318_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='migrations',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
