# Generated by Django 3.2.13 on 2022-04-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcheck", "0006_auto_20220417_0042"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pytestresult",
            options={
                "verbose_name": "Pytest Result",
                "verbose_name_plural": "Pytest Results",
            },
        ),
        migrations.AlterField(
            model_name="pytestresult",
            name="duration",
            field=models.DurationField(help_text="Test duration."),
        ),
    ]
