# Generated by Django 3.2.13 on 2022-04-17 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0007_auto_20220417_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pylintresult',
            old_name='endColumn',
            new_name='end_column',
        ),
        migrations.RenameField(
            model_name='pylintresult',
            old_name='endLine',
            new_name='end_line',
        ),
    ]
