# Generated by Django 3.1.7 on 2021-03-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0007_pullrequest_migrations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pullrequest',
            options={'verbose_name': 'Pull Request', 'verbose_name_plural': 'Pull Requests'},
        ),
    ]
