# Generated by Django 3.2.13 on 2022-04-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0008_auto_20220417_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pylintresult',
            name='message',
            field=models.TextField(help_text='Text of the message.'),
        ),
    ]
