# Generated by Django 3.2 on 2021-04-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0008_auto_20210318_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
