# Generated by Django 4.1 on 2022-08-23 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcheck", "0009_alter_pylintresult_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="pylintreport",
            name="score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
    ]
