# Generated by Django 3.2.4 on 2021-08-03 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0009_alter_pullrequest_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pullrequest',
            options={'get_latest_by': 'number', 'verbose_name': 'Pull Request', 'verbose_name_plural': 'Pull Requests'},
        ),
    ]
