# Generated by Django 3.2.11 on 2022-01-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0010_alter_pullrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='last_commit_sha',
            field=models.CharField(blank=True, help_text='SHA of the last commit.', max_length=50, null=True),
        ),
    ]
