# Generated by Django 4.1 on 2022-08-23 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcheck", "0010_pylintreport_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="coveragereport",
            name="pull_request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="healthcheck.pullrequest",
            ),
        ),
        migrations.AddField(
            model_name="pylintreport",
            name="pull_request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="healthcheck.pullrequest",
            ),
        ),
        migrations.AddField(
            model_name="pytestreport",
            name="pull_request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="healthcheck.pullrequest",
            ),
        ),
    ]
