name: Python application

on:
  pull_request:
    branches: [master]

jobs:
  build:
    if: ${{ github.actor != 'github-actions' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev --skip-lock
      - name: Run quality check
        env:
          APP_ENV: TEST
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        run: |
          make qa
      - name: Upload report files
        env:
          APP_ENV: TEST
          MONO_TOKEN: ${{ secrets.MONO_TOKEN }}
        run: |
          make upload_pytest_report
          make upload_coverage_report
