name: Python application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Run tests
        env:
          APP_ENV: TEST
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        run: |
          make qa
      - name: Get current version tag
        run: |
          export MONO_VERSION=$(pipenv run cz version --project)
          echo Current version is $MONO_VERSION
      - name: Check if version was assigned to var
        run: |
          echo Current version is ${{ env.MONO_VERSION }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actions
          message: 'Update changes made by github actions'
          add: '.'
          push: origin master
          # tag: ${{ env.MONO_VERSION }}
